import { ExpertListDTO } from '../types/expert.dto';
import { ExpertSearchResult } from './expertSearch.service';

export const EXPERT_DONOR_REFERENCE_FORMATS = [
  'Danida CV/Reference',
  'Europass',
  'UNDP',
  'OJ World Bank Reference',
  'World Bank CV',
];

const sanitizeFilePart = (value: string) =>
  value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'expert-cv';

const getSearchExpertName = (expert: ExpertSearchResult) =>
  expert.fullName || [expert.firstName, expert.lastName].filter(Boolean).join(' ') || `Expert ${expert.id}`;

export function downloadExpertCvFile(expert: ExpertListDTO | ExpertSearchResult, format = 'Full CV') {
  const isSearchExpert = 'fullName' in expert || typeof expert.id === 'number';
  const name = isSearchExpert
    ? getSearchExpertName(expert as ExpertSearchResult)
    : `${(expert as ExpertListDTO).firstName} ${(expert as ExpertListDTO).lastName}`.trim();
  const title = isSearchExpert ? (expert as ExpertSearchResult).currentPosition || (expert as ExpertSearchResult).title : (expert as ExpertListDTO).title;
  const country = isSearchExpert ? (expert as ExpertSearchResult).country?.name : (expert as ExpertListDTO).country;
  const sectors = isSearchExpert
    ? ((expert as ExpertSearchResult).sectors || []).map((sector) => sector.sectorName || sector.sectorCode).filter(Boolean)
    : (expert as ExpertListDTO).sectors;
  const skills = isSearchExpert
    ? ((expert as ExpertSearchResult).skills || []).map((skill) => skill.skillName).filter(Boolean)
    : (expert as ExpertListDTO).skills;

  const content = [
    `${format}`,
    '',
    `Name: ${name}`,
    `Expert ID: ${expert.id}`,
    `Title: ${title || 'N/A'}`,
    `Country: ${country || 'N/A'}`,
    `Years of experience: ${(expert as ExpertSearchResult).yearsExperience ?? (expert as ExpertListDTO).yearsOfExperience ?? 'N/A'}`,
    '',
    'Expertise',
    sectors.join(', ') || 'N/A',
    '',
    'Skills',
    skills.join(', ') || 'N/A',
    '',
    'Generated by Assortis',
  ].join('\n');

  const extension = format === 'Full CV' ? 'txt' : 'docx';
  const fileName = `${sanitizeFilePart(name)}-${sanitizeFilePart(format)}.${extension}`;
  const blob = new Blob([content], {
    type: extension === 'docx'
      ? 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
      : 'text/plain;charset=utf-8',
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);

  return fileName;
}
