// Countries Configuration
// Complete list of countries for location selection

export const COUNTRIES = [
  // Africa
  { code: 'DZ', name: { en: 'Algeria', fr: 'Algérie', es: 'Argelia' } },
  { code: 'AO', name: { en: 'Angola', fr: 'Angola', es: 'Angola' } },
  { code: 'BJ', name: { en: 'Benin', fr: 'Bénin', es: 'Benín' } },
  { code: 'BW', name: { en: 'Botswana', fr: 'Botswana', es: 'Botsuana' } },
  { code: 'BF', name: { en: 'Burkina Faso', fr: 'Burkina Faso', es: 'Burkina Faso' } },
  { code: 'BI', name: { en: 'Burundi', fr: 'Burundi', es: 'Burundi' } },
  { code: 'CM', name: { en: 'Cameroon', fr: 'Cameroun', es: 'Camerún' } },
  { code: 'CV', name: { en: 'Cape Verde', fr: 'Cap-Vert', es: 'Cabo Verde' } },
  { code: 'CF', name: { en: 'Central African Republic', fr: 'République Centrafricaine', es: 'República Centroafricana' } },
  { code: 'TD', name: { en: 'Chad', fr: 'Tchad', es: 'Chad' } },
  { code: 'KM', name: { en: 'Comoros', fr: 'Comores', es: 'Comoras' } },
  { code: 'CG', name: { en: 'Congo', fr: 'Congo', es: 'Congo' } },
  { code: 'CD', name: { en: 'Democratic Republic of the Congo', fr: 'République Démocratique du Congo', es: 'República Democrática del Congo' } },
  { code: 'CI', name: { en: 'Côte d\'Ivoire', fr: 'Côte d\'Ivoire', es: 'Costa de Marfil' } },
  { code: 'DJ', name: { en: 'Djibouti', fr: 'Djibouti', es: 'Yibuti' } },
  { code: 'EG', name: { en: 'Egypt', fr: 'Égypte', es: 'Egipto' } },
  { code: 'GQ', name: { en: 'Equatorial Guinea', fr: 'Guinée Équatoriale', es: 'Guinea Ecuatorial' } },
  { code: 'ER', name: { en: 'Eritrea', fr: 'Érythrée', es: 'Eritrea' } },
  { code: 'ET', name: { en: 'Ethiopia', fr: 'Éthiopie', es: 'Etiopía' } },
  { code: 'GA', name: { en: 'Gabon', fr: 'Gabon', es: 'Gabón' } },
  { code: 'GM', name: { en: 'Gambia', fr: 'Gambie', es: 'Gambia' } },
  { code: 'GH', name: { en: 'Ghana', fr: 'Ghana', es: 'Ghana' } },
  { code: 'GN', name: { en: 'Guinea', fr: 'Guinée', es: 'Guinea' } },
  { code: 'GW', name: { en: 'Guinea-Bissau', fr: 'Guinée-Bissau', es: 'Guinea-Bisáu' } },
  { code: 'KE', name: { en: 'Kenya', fr: 'Kenya', es: 'Kenia' } },
  { code: 'LS', name: { en: 'Lesotho', fr: 'Lesotho', es: 'Lesoto' } },
  { code: 'LR', name: { en: 'Liberia', fr: 'Libéria', es: 'Liberia' } },
  { code: 'LY', name: { en: 'Libya', fr: 'Libye', es: 'Libia' } },
  { code: 'MG', name: { en: 'Madagascar', fr: 'Madagascar', es: 'Madagascar' } },
  { code: 'MW', name: { en: 'Malawi', fr: 'Malawi', es: 'Malaui' } },
  { code: 'ML', name: { en: 'Mali', fr: 'Mali', es: 'Malí' } },
  { code: 'MR', name: { en: 'Mauritania', fr: 'Mauritanie', es: 'Mauritania' } },
  { code: 'MU', name: { en: 'Mauritius', fr: 'Maurice', es: 'Mauricio' } },
  { code: 'MA', name: { en: 'Morocco', fr: 'Maroc', es: 'Marruecos' } },
  { code: 'MZ', name: { en: 'Mozambique', fr: 'Mozambique', es: 'Mozambique' } },
  { code: 'NA', name: { en: 'Namibia', fr: 'Namibie', es: 'Namibia' } },
  { code: 'NE', name: { en: 'Niger', fr: 'Niger', es: 'Níger' } },
  { code: 'NG', name: { en: 'Nigeria', fr: 'Nigéria', es: 'Nigeria' } },
  { code: 'RW', name: { en: 'Rwanda', fr: 'Rwanda', es: 'Ruanda' } },
  { code: 'ST', name: { en: 'São Tomé and Príncipe', fr: 'Sao Tomé-et-Principe', es: 'Santo Tomé y Príncipe' } },
  { code: 'SN', name: { en: 'Senegal', fr: 'Sénégal', es: 'Senegal' } },
  { code: 'SC', name: { en: 'Seychelles', fr: 'Seychelles', es: 'Seychelles' } },
  { code: 'SL', name: { en: 'Sierra Leone', fr: 'Sierra Leone', es: 'Sierra Leona' } },
  { code: 'SO', name: { en: 'Somalia', fr: 'Somalie', es: 'Somalia' } },
  { code: 'ZA', name: { en: 'South Africa', fr: 'Afrique du Sud', es: 'Sudáfrica' } },
  { code: 'SS', name: { en: 'South Sudan', fr: 'Soudan du Sud', es: 'Sudán del Sur' } },
  { code: 'SD', name: { en: 'Sudan', fr: 'Soudan', es: 'Sudán' } },
  { code: 'SZ', name: { en: 'Eswatini', fr: 'Eswatini', es: 'Esuatini' } },
  { code: 'TZ', name: { en: 'Tanzania', fr: 'Tanzanie', es: 'Tanzania' } },
  { code: 'TG', name: { en: 'Togo', fr: 'Togo', es: 'Togo' } },
  { code: 'TN', name: { en: 'Tunisia', fr: 'Tunisie', es: 'Túnez' } },
  { code: 'UG', name: { en: 'Uganda', fr: 'Ouganda', es: 'Uganda' } },
  { code: 'ZM', name: { en: 'Zambia', fr: 'Zambie', es: 'Zambia' } },
  { code: 'ZW', name: { en: 'Zimbabwe', fr: 'Zimbabwe', es: 'Zimbabue' } },

  // Americas
  { code: 'AR', name: { en: 'Argentina', fr: 'Argentine', es: 'Argentina' } },
  { code: 'BS', name: { en: 'Bahamas', fr: 'Bahamas', es: 'Bahamas' } },
  { code: 'BB', name: { en: 'Barbados', fr: 'Barbade', es: 'Barbados' } },
  { code: 'BZ', name: { en: 'Belize', fr: 'Belize', es: 'Belice' } },
  { code: 'BO', name: { en: 'Bolivia', fr: 'Bolivie', es: 'Bolivia' } },
  { code: 'BR', name: { en: 'Brazil', fr: 'Brésil', es: 'Brasil' } },
  { code: 'CA', name: { en: 'Canada', fr: 'Canada', es: 'Canadá' } },
  { code: 'CL', name: { en: 'Chile', fr: 'Chili', es: 'Chile' } },
  { code: 'CO', name: { en: 'Colombia', fr: 'Colombie', es: 'Colombia' } },
  { code: 'CR', name: { en: 'Costa Rica', fr: 'Costa Rica', es: 'Costa Rica' } },
  { code: 'CU', name: { en: 'Cuba', fr: 'Cuba', es: 'Cuba' } },
  { code: 'DM', name: { en: 'Dominica', fr: 'Dominique', es: 'Dominica' } },
  { code: 'DO', name: { en: 'Dominican Republic', fr: 'République Dominicaine', es: 'República Dominicana' } },
  { code: 'EC', name: { en: 'Ecuador', fr: 'Équateur', es: 'Ecuador' } },
  { code: 'SV', name: { en: 'El Salvador', fr: 'Salvador', es: 'El Salvador' } },
  { code: 'GD', name: { en: 'Grenada', fr: 'Grenade', es: 'Granada' } },
  { code: 'GT', name: { en: 'Guatemala', fr: 'Guatemala', es: 'Guatemala' } },
  { code: 'GY', name: { en: 'Guyana', fr: 'Guyana', es: 'Guyana' } },
  { code: 'HT', name: { en: 'Haiti', fr: 'Haïti', es: 'Haití' } },
  { code: 'HN', name: { en: 'Honduras', fr: 'Honduras', es: 'Honduras' } },
  { code: 'JM', name: { en: 'Jamaica', fr: 'Jamaïque', es: 'Jamaica' } },
  { code: 'MX', name: { en: 'Mexico', fr: 'Mexique', es: 'México' } },
  { code: 'NI', name: { en: 'Nicaragua', fr: 'Nicaragua', es: 'Nicaragua' } },
  { code: 'PA', name: { en: 'Panama', fr: 'Panama', es: 'Panamá' } },
  { code: 'PY', name: { en: 'Paraguay', fr: 'Paraguay', es: 'Paraguay' } },
  { code: 'PE', name: { en: 'Peru', fr: 'Pérou', es: 'Perú' } },
  { code: 'SR', name: { en: 'Suriname', fr: 'Suriname', es: 'Surinam' } },
  { code: 'TT', name: { en: 'Trinidad and Tobago', fr: 'Trinité-et-Tobago', es: 'Trinidad y Tobago' } },
  { code: 'US', name: { en: 'United States', fr: 'États-Unis', es: 'Estados Unidos' } },
  { code: 'UY', name: { en: 'Uruguay', fr: 'Uruguay', es: 'Uruguay' } },
  { code: 'VE', name: { en: 'Venezuela', fr: 'Venezuela', es: 'Venezuela' } },

  // Asia
  { code: 'AF', name: { en: 'Afghanistan', fr: 'Afghanistan', es: 'Afganistán' } },
  { code: 'BD', name: { en: 'Bangladesh', fr: 'Bangladesh', es: 'Bangladés' } },
  { code: 'BT', name: { en: 'Bhutan', fr: 'Bhoutan', es: 'Bután' } },
  { code: 'BN', name: { en: 'Brunei', fr: 'Brunei', es: 'Brunéi' } },
  { code: 'KH', name: { en: 'Cambodia', fr: 'Cambodge', es: 'Camboya' } },
  { code: 'CN', name: { en: 'China', fr: 'Chine', es: 'China' } },
  { code: 'IN', name: { en: 'India', fr: 'Inde', es: 'India' } },
  { code: 'ID', name: { en: 'Indonesia', fr: 'Indonésie', es: 'Indonesia' } },
  { code: 'JP', name: { en: 'Japan', fr: 'Japon', es: 'Japón' } },
  { code: 'KZ', name: { en: 'Kazakhstan', fr: 'Kazakhstan', es: 'Kazajistán' } },
  { code: 'KG', name: { en: 'Kyrgyzstan', fr: 'Kirghizistan', es: 'Kirguistán' } },
  { code: 'LA', name: { en: 'Laos', fr: 'Laos', es: 'Laos' } },
  { code: 'MY', name: { en: 'Malaysia', fr: 'Malaisie', es: 'Malasia' } },
  { code: 'MV', name: { en: 'Maldives', fr: 'Maldives', es: 'Maldivas' } },
  { code: 'MN', name: { en: 'Mongolia', fr: 'Mongolie', es: 'Mongolia' } },
  { code: 'MM', name: { en: 'Myanmar', fr: 'Myanmar', es: 'Myanmar' } },
  { code: 'NP', name: { en: 'Nepal', fr: 'Népal', es: 'Nepal' } },
  { code: 'KP', name: { en: 'North Korea', fr: 'Corée du Nord', es: 'Corea del Norte' } },
  { code: 'PK', name: { en: 'Pakistan', fr: 'Pakistan', es: 'Pakistán' } },
  { code: 'PH', name: { en: 'Philippines', fr: 'Philippines', es: 'Filipinas' } },
  { code: 'SG', name: { en: 'Singapore', fr: 'Singapour', es: 'Singapur' } },
  { code: 'KR', name: { en: 'South Korea', fr: 'Corée du Sud', es: 'Corea del Sur' } },
  { code: 'LK', name: { en: 'Sri Lanka', fr: 'Sri Lanka', es: 'Sri Lanka' } },
  { code: 'TJ', name: { en: 'Tajikistan', fr: 'Tadjikistan', es: 'Tayikistán' } },
  { code: 'TH', name: { en: 'Thailand', fr: 'Thaïlande', es: 'Tailandia' } },
  { code: 'TL', name: { en: 'Timor-Leste', fr: 'Timor-Leste', es: 'Timor Oriental' } },
  { code: 'TM', name: { en: 'Turkmenistan', fr: 'Turkménistan', es: 'Turkmenistán' } },
  { code: 'UZ', name: { en: 'Uzbekistan', fr: 'Ouzbékistan', es: 'Uzbekistán' } },
  { code: 'VN', name: { en: 'Vietnam', fr: 'Vietnam', es: 'Vietnam' } },

  // Europe
  { code: 'AL', name: { en: 'Albania', fr: 'Albanie', es: 'Albania' } },
  { code: 'AD', name: { en: 'Andorra', fr: 'Andorre', es: 'Andorra' } },
  { code: 'AT', name: { en: 'Austria', fr: 'Autriche', es: 'Austria' } },
  { code: 'BY', name: { en: 'Belarus', fr: 'Biélorussie', es: 'Bielorrusia' } },
  { code: 'BE', name: { en: 'Belgium', fr: 'Belgique', es: 'Bélgica' } },
  { code: 'BA', name: { en: 'Bosnia and Herzegovina', fr: 'Bosnie-Herzégovine', es: 'Bosnia y Herzegovina' } },
  { code: 'BG', name: { en: 'Bulgaria', fr: 'Bulgarie', es: 'Bulgaria' } },
  { code: 'HR', name: { en: 'Croatia', fr: 'Croatie', es: 'Croacia' } },
  { code: 'CY', name: { en: 'Cyprus', fr: 'Chypre', es: 'Chipre' } },
  { code: 'CZ', name: { en: 'Czech Republic', fr: 'République Tchèque', es: 'República Checa' } },
  { code: 'DK', name: { en: 'Denmark', fr: 'Danemark', es: 'Dinamarca' } },
  { code: 'EE', name: { en: 'Estonia', fr: 'Estonie', es: 'Estonia' } },
  { code: 'FI', name: { en: 'Finland', fr: 'Finlande', es: 'Finlandia' } },
  { code: 'FR', name: { en: 'France', fr: 'France', es: 'Francia' } },
  { code: 'DE', name: { en: 'Germany', fr: 'Allemagne', es: 'Alemania' } },
  { code: 'GR', name: { en: 'Greece', fr: 'Grèce', es: 'Grecia' } },
  { code: 'HU', name: { en: 'Hungary', fr: 'Hongrie', es: 'Hungría' } },
  { code: 'IS', name: { en: 'Iceland', fr: 'Islande', es: 'Islandia' } },
  { code: 'IE', name: { en: 'Ireland', fr: 'Irlande', es: 'Irlanda' } },
  { code: 'IT', name: { en: 'Italy', fr: 'Italie', es: 'Italia' } },
  { code: 'LV', name: { en: 'Latvia', fr: 'Lettonie', es: 'Letonia' } },
  { code: 'LI', name: { en: 'Liechtenstein', fr: 'Liechtenstein', es: 'Liechtenstein' } },
  { code: 'LT', name: { en: 'Lithuania', fr: 'Lituanie', es: 'Lituania' } },
  { code: 'LU', name: { en: 'Luxembourg', fr: 'Luxembourg', es: 'Luxemburgo' } },
  { code: 'MT', name: { en: 'Malta', fr: 'Malte', es: 'Malta' } },
  { code: 'MD', name: { en: 'Moldova', fr: 'Moldavie', es: 'Moldavia' } },
  { code: 'MC', name: { en: 'Monaco', fr: 'Monaco', es: 'Mónaco' } },
  { code: 'ME', name: { en: 'Montenegro', fr: 'Monténégro', es: 'Montenegro' } },
  { code: 'NL', name: { en: 'Netherlands', fr: 'Pays-Bas', es: 'Países Bajos' } },
  { code: 'MK', name: { en: 'North Macedonia', fr: 'Macédoine du Nord', es: 'Macedonia del Norte' } },
  { code: 'NO', name: { en: 'Norway', fr: 'Norvège', es: 'Noruega' } },
  { code: 'PL', name: { en: 'Poland', fr: 'Pologne', es: 'Polonia' } },
  { code: 'PT', name: { en: 'Portugal', fr: 'Portugal', es: 'Portugal' } },
  { code: 'RO', name: { en: 'Romania', fr: 'Roumanie', es: 'Rumania' } },
  { code: 'RU', name: { en: 'Russia', fr: 'Russie', es: 'Rusia' } },
  { code: 'SM', name: { en: 'San Marino', fr: 'Saint-Marin', es: 'San Marino' } },
  { code: 'RS', name: { en: 'Serbia', fr: 'Serbie', es: 'Serbia' } },
  { code: 'SK', name: { en: 'Slovakia', fr: 'Slovaquie', es: 'Eslovaquia' } },
  { code: 'SI', name: { en: 'Slovenia', fr: 'Slovénie', es: 'Eslovenia' } },
  { code: 'ES', name: { en: 'Spain', fr: 'Espagne', es: 'España' } },
  { code: 'SE', name: { en: 'Sweden', fr: 'Suède', es: 'Suecia' } },
  { code: 'CH', name: { en: 'Switzerland', fr: 'Suisse', es: 'Suiza' } },
  { code: 'TR', name: { en: 'Turkey', fr: 'Turquie', es: 'Turquía' } },
  { code: 'UA', name: { en: 'Ukraine', fr: 'Ukraine', es: 'Ucrania' } },
  { code: 'GB', name: { en: 'United Kingdom', fr: 'Royaume-Uni', es: 'Reino Unido' } },
  { code: 'VA', name: { en: 'Vatican City', fr: 'Vatican', es: 'Ciudad del Vaticano' } },

  // Middle East
  { code: 'BH', name: { en: 'Bahrain', fr: 'Bahreïn', es: 'Baréin' } },
  { code: 'IR', name: { en: 'Iran', fr: 'Iran', es: 'Irán' } },
  { code: 'IQ', name: { en: 'Iraq', fr: 'Irak', es: 'Irak' } },
  { code: 'IL', name: { en: 'Israel', fr: 'Israël', es: 'Israel' } },
  { code: 'JO', name: { en: 'Jordan', fr: 'Jordanie', es: 'Jordania' } },
  { code: 'KW', name: { en: 'Kuwait', fr: 'Koweït', es: 'Kuwait' } },
  { code: 'LB', name: { en: 'Lebanon', fr: 'Liban', es: 'Líbano' } },
  { code: 'OM', name: { en: 'Oman', fr: 'Oman', es: 'Omán' } },
  { code: 'PS', name: { en: 'Palestine', fr: 'Palestine', es: 'Palestina' } },
  { code: 'QA', name: { en: 'Qatar', fr: 'Qatar', es: 'Catar' } },
  { code: 'SA', name: { en: 'Saudi Arabia', fr: 'Arabie Saoudite', es: 'Arabia Saudita' } },
  { code: 'SY', name: { en: 'Syria', fr: 'Syrie', es: 'Siria' } },
  { code: 'AE', name: { en: 'United Arab Emirates', fr: 'Émirats Arabes Unis', es: 'Emiratos Árabes Unidos' } },
  { code: 'YE', name: { en: 'Yemen', fr: 'Yémen', es: 'Yemen' } },

  // Oceania
  { code: 'AU', name: { en: 'Australia', fr: 'Australie', es: 'Australia' } },
  { code: 'FJ', name: { en: 'Fiji', fr: 'Fidji', es: 'Fiyi' } },
  { code: 'KI', name: { en: 'Kiribati', fr: 'Kiribati', es: 'Kiribati' } },
  { code: 'MH', name: { en: 'Marshall Islands', fr: 'Îles Marshall', es: 'Islas Marshall' } },
  { code: 'FM', name: { en: 'Micronesia', fr: 'Micronésie', es: 'Micronesia' } },
  { code: 'NR', name: { en: 'Nauru', fr: 'Nauru', es: 'Nauru' } },
  { code: 'NZ', name: { en: 'New Zealand', fr: 'Nouvelle-Zélande', es: 'Nueva Zelanda' } },
  { code: 'PW', name: { en: 'Palau', fr: 'Palaos', es: 'Palaos' } },
  { code: 'PG', name: { en: 'Papua New Guinea', fr: 'Papouasie-Nouvelle-Guinée', es: 'Papúa Nueva Guinea' } },
  { code: 'WS', name: { en: 'Samoa', fr: 'Samoa', es: 'Samoa' } },
  { code: 'SB', name: { en: 'Solomon Islands', fr: 'Îles Salomon', es: 'Islas Salomón' } },
  { code: 'TO', name: { en: 'Tonga', fr: 'Tonga', es: 'Tonga' } },
  { code: 'TV', name: { en: 'Tuvalu', fr: 'Tuvalu', es: 'Tuvalu' } },
  { code: 'VU', name: { en: 'Vanuatu', fr: 'Vanuatu', es: 'Vanuatu' } },
];

export function getCountryName(code: string, language: 'en' | 'fr' | 'es'): string {
  const country = COUNTRIES.find(c => c.code === code);
  return country ? country.name[language] : code;
}

export function getCountriesSorted(language: 'en' | 'fr' | 'es') {
  return [...COUNTRIES].sort((a, b) => 
    a.name[language].localeCompare(b.name[language])
  );
}
