import { CountryEnum, RegionEnum } from '@app/types/tender.dto';

export const ORGANIZATION_REGION_LABELS: Record<RegionEnum, string> = {
  [RegionEnum.CENTRAL_EASTERN_EUROPE]: 'Central & Eastern Europe',
  [RegionEnum.SOUTHEASTERN_EUROPE]: 'Southeastern Europe',
  [RegionEnum.WESTERN_EUROPE]: 'Western Europe',
  [RegionEnum.CENTRAL_AFRICA]: 'Central Africa',
  [RegionEnum.EAST_AFRICA]: 'East Africa',
  [RegionEnum.NORTH_AFRICA]: 'North Africa',
  [RegionEnum.SOUTHERN_AFRICA]: 'Southern Africa',
  [RegionEnum.WEST_AFRICA]: 'West Africa',
  [RegionEnum.CENTRAL_ASIA]: 'Central Asia',
  [RegionEnum.MIDDLE_EAST]: 'Middle East',
  [RegionEnum.NORTHEAST_ASIA]: 'Northeast Asia',
  [RegionEnum.SOUTHEAST_ASIA]: 'Southeast Asia',
  [RegionEnum.SOUTH_ASIA]: 'South Asia',
  [RegionEnum.OCEANIA]: 'Oceania',
  [RegionEnum.CENTRAL_AMERICA]: 'Central America',
  [RegionEnum.NORTH_AMERICA]: 'North America',
  [RegionEnum.SOUTH_AMERICA]: 'South America',
};

export const ORGANIZATION_REGION_COUNTRY_MAP: Record<RegionEnum, CountryEnum[]> = {
  [RegionEnum.CENTRAL_EASTERN_EUROPE]: [
    CountryEnum.POLAND,
    CountryEnum.CZECK_REPUBLIC,
    CountryEnum.HUNGARY,
    CountryEnum.SLOVAKIA,
    CountryEnum.SLOVENIA,
  ],
  [RegionEnum.SOUTHEASTERN_EUROPE]: [
    CountryEnum.ALBANIA,
    CountryEnum.BOSNIA_HERZEGOVINA,
    CountryEnum.BULGARIA,
    CountryEnum.CROATIA,
    CountryEnum.MONTENEGRO,
    CountryEnum.SERBIA,
  ],
  [RegionEnum.WESTERN_EUROPE]: [
    CountryEnum.FRANCE,
    CountryEnum.GERMANY,
    CountryEnum.UNITED_KINGDOM,
    CountryEnum.SPAIN,
    CountryEnum.ITALY,
    CountryEnum.BELGIUM,
    CountryEnum.NETHERLANDS,
    CountryEnum.SWITZERLAND,
    CountryEnum.AUSTRIA,
    CountryEnum.PORTUGAL,
  ],
  [RegionEnum.CENTRAL_AFRICA]: [
    CountryEnum.CAMEROON,
    CountryEnum.CHAD,
    CountryEnum.CENTRAL_AFRICAN_REPUBLIC,
    CountryEnum.CONGO,
    CountryEnum.DEMOCRATIC_REPUBLIC_OF_CONGO,
    CountryEnum.GABON,
  ],
  [RegionEnum.EAST_AFRICA]: [
    CountryEnum.KENYA,
    CountryEnum.TANZANIA,
    CountryEnum.UGANDA,
    CountryEnum.ETHIOPIA,
    CountryEnum.RWANDA,
    CountryEnum.BURUNDI,
    CountryEnum.SOMALIA,
  ],
  [RegionEnum.NORTH_AFRICA]: [
    CountryEnum.EGYPT,
    CountryEnum.MOROCCO,
    CountryEnum.TUNISIA,
    CountryEnum.ALGERIA,
    CountryEnum.LIBYA,
  ],
  [RegionEnum.SOUTHERN_AFRICA]: [
    CountryEnum.SOUTH_AFRICA,
    CountryEnum.ZIMBABWE,
    CountryEnum.ZAMBIA,
    CountryEnum.MOZAMBIQUE,
    CountryEnum.BOTSWANA,
    CountryEnum.NAMIBIA,
  ],
  [RegionEnum.WEST_AFRICA]: [
    CountryEnum.NIGERIA,
    CountryEnum.GHANA,
    CountryEnum.SENEGAL,
    CountryEnum.IVORY_COAST,
    CountryEnum.MALI,
    CountryEnum.NIGER,
    CountryEnum.BURKINA_FASO,
    CountryEnum.BENIN,
    CountryEnum.TOGO,
  ],
  [RegionEnum.CENTRAL_ASIA]: [
    CountryEnum.KAZAKHSTAN,
    CountryEnum.UZBEKISTAN,
    CountryEnum.TURKMENISTAN,
    CountryEnum.KYRGYZSTAN,
    CountryEnum.TAJIKISTAN,
  ],
  [RegionEnum.MIDDLE_EAST]: [
    CountryEnum.SAUDI_ARABIA,
    CountryEnum.UAE,
    CountryEnum.QATAR,
    CountryEnum.KUWAIT,
    CountryEnum.BAHRAIN,
    CountryEnum.OMAN,
    CountryEnum.JORDAN,
    CountryEnum.LEBANON,
    CountryEnum.IRAQ,
    CountryEnum.YEMEN,
  ],
  [RegionEnum.NORTHEAST_ASIA]: [
    CountryEnum.CHINA,
    CountryEnum.JAPAN,
    CountryEnum.SOUTH_KOREA,
    CountryEnum.NORTH_KOREA,
    CountryEnum.MONGOLIA,
  ],
  [RegionEnum.SOUTHEAST_ASIA]: [
    CountryEnum.THAILAND,
    CountryEnum.VIETNAM,
    CountryEnum.PHILIPPINES,
    CountryEnum.INDONESIA,
    CountryEnum.MALAYSIA,
    CountryEnum.SINGAPORE,
    CountryEnum.MYANMAR,
    CountryEnum.CAMBODIA,
  ],
  [RegionEnum.SOUTH_ASIA]: [
    CountryEnum.INDIA,
    CountryEnum.PAKISTAN,
    CountryEnum.BANGLADESH,
    CountryEnum.SRI_LANKA,
    CountryEnum.NEPAL,
    CountryEnum.AFGHANISTAN,
  ],
  [RegionEnum.OCEANIA]: [
    CountryEnum.AUSTRALIA,
    CountryEnum.NEW_ZEALAND,
    CountryEnum.FIJI,
    CountryEnum.PAPUA_NEW_GUINEA,
  ],
  [RegionEnum.CENTRAL_AMERICA]: [
    CountryEnum.MEXICO,
    CountryEnum.GUATEMALA,
    CountryEnum.HONDURAS,
    CountryEnum.EL_SALVADOR,
    CountryEnum.NICARAGUA,
    CountryEnum.COSTA_RICA,
    CountryEnum.PANAMA,
  ],
  [RegionEnum.NORTH_AMERICA]: [CountryEnum.CANADA, CountryEnum.UNITED_STATES],
  [RegionEnum.SOUTH_AMERICA]: [CountryEnum.ARGENTINA, CountryEnum.BOLIVIA, CountryEnum.BRAZIL, CountryEnum.PY],
};
