// Professional Configuration
// Predefined lists for professional fields to ensure data quality

// Common professional titles in development sector
export const PROFESSIONAL_TITLES = [
  'Project Manager',
  'Senior Project Manager',
  'Program Manager',
  'Team Leader',
  'Technical Advisor',
  'Senior Technical Advisor',
  'Chief Technical Advisor',
  'Consultant',
  'Senior Consultant',
  'Expert Consultant',
  'Sector Specialist',
  'Technical Specialist',
  'Program Coordinator',
  'Project Coordinator',
  'M&E Specialist',
  'Monitoring & Evaluation Officer',
  'Research Officer',
  'Research Analyst',
  'Policy Advisor',
  'Capacity Building Specialist',
  'Training Specialist',
  'Gender Specialist',
  'Environmental Specialist',
  'Climate Change Specialist',
  'Infrastructure Engineer',
  'Water & Sanitation Engineer',
  'Public Health Specialist',
  'Education Specialist',
  'Agriculture Specialist',
  'Governance Specialist',
  'Financial Analyst',
  'Grant Manager',
  'Procurement Specialist',
  'Communications Officer',
  'Advocacy Officer',
  'Humanitarian Coordinator',
  'Emergency Response Coordinator',
  'Field Officer',
  'Country Director',
  'Deputy Country Director',
  'Program Director',
  'Operations Manager',
  'Human Resources Manager',
  'Finance Manager',
  'Administration Manager',
  'Logistics Coordinator',
  'Partnership Manager',
  'Other',
];

// Common technical skills
export const COMMON_SKILLS = [
  'Project Management',
  'Program Management',
  'Stakeholder Engagement',
  'Budget Planning',
  'Financial Management',
  'Grant Management',
  'Proposal Writing',
  'Report Writing',
  'Monitoring & Evaluation',
  'Data Analysis',
  'Statistical Analysis',
  'Research Methodology',
  'Policy Analysis',
  'Strategic Planning',
  'Risk Management',
  'Team Leadership',
  'Team Building',
  'Capacity Building',
  'Training & Facilitation',
  'Change Management',
  'Communication Skills',
  'Presentation Skills',
  'Negotiation',
  'Conflict Resolution',
  'Partnership Development',
  'Advocacy',
  'Community Mobilization',
  'Participatory Approaches',
  'Gender Mainstreaming',
  'Climate Change Adaptation',
  'Environmental Impact Assessment',
  'Logical Framework Approach',
  'Theory of Change',
  'Results-Based Management',
  'Procurement',
  'Contract Management',
  'Human Rights-Based Approach',
  'Do No Harm',
  'Emergency Response',
  'Humanitarian Principles',
  'SPHERE Standards',
  'GIS Mapping',
  'Database Management',
  'SPSS',
  'STATA',
  'R Programming',
  'Python',
  'Excel (Advanced)',
  'Power BI',
  'Tableau',
  'AutoCAD',
  'ArcGIS',
  'Project Management Software',
  'MS Project',
  'Primavera',
];

// Common languages
export const COMMON_LANGUAGES = [
  'English',
  'French',
  'Spanish',
  'Arabic',
  'Portuguese',
  'Chinese (Mandarin)',
  'Russian',
  'German',
  'Italian',
  'Japanese',
  'Korean',
  'Dutch',
  'Swedish',
  'Norwegian',
  'Danish',
  'Finnish',
  'Polish',
  'Turkish',
  'Hindi',
  'Urdu',
  'Bengali',
  'Swahili',
  'Hausa',
  'Amharic',
  'Somali',
  'Kinyarwanda',
  'Lingala',
  'Wolof',
  'Bambara',
  'Other',
];

// Common certifications
export const COMMON_CERTIFICATIONS = [
  'PMP - Project Management Professional',
  'PRINCE2 Foundation',
  'PRINCE2 Practitioner',
  'Agile Certified Practitioner (PMI-ACP)',
  'Certified ScrumMaster (CSM)',
  'ITIL Foundation',
  'Six Sigma Green Belt',
  'Six Sigma Black Belt',
  'Certified Public Accountant (CPA)',
  'Chartered Financial Analyst (CFA)',
  'Project Cycle Management (PCM)',
  'Monitoring & Evaluation Certification',
  'Gender Equality Certification',
  'Climate Change Certification',
  'Humanitarian Standards Certification',
  'SPHERE Standards Training',
  'Child Protection Certification',
  'Gender-Based Violence Response',
  'WASH Specialist Certification',
  'Public Health Certification',
  'Environmental Impact Assessment',
  'ISO 9001 Lead Auditor',
  'ISO 14001 Environmental Management',
  'LEED Accreditation',
  'Engineering License',
  'Medical License',
  'Teaching Certification',
  'Social Work License',
  'Other',
];

// Years of experience options
export const YEARS_OF_EXPERIENCE = [
  { value: '0-1', label: '0-1 years' },
  { value: '1-2', label: '1-2 years' },
  { value: '2-3', label: '2-3 years' },
  { value: '3-5', label: '3-5 years' },
  { value: '5-7', label: '5-7 years' },
  { value: '7-10', label: '7-10 years' },
  { value: '10-15', label: '10-15 years' },
  { value: '15-20', label: '15-20 years' },
  { value: '20+', label: '20+ years' },
];

// Generate years for dropdowns (from 1950 to current year + 10)
export function getYearOptions(): number[] {
  const currentYear = new Date().getFullYear();
  const years: number[] = [];
  for (let year = currentYear + 10; year >= 1950; year--) {
    years.push(year);
  }
  return years;
}

// Generate future years for certifications expiry (current year to +20 years)
export function getFutureYearOptions(): number[] {
  const currentYear = new Date().getFullYear();
  const years: number[] = [];
  for (let year = currentYear; year <= currentYear + 20; year++) {
    years.push(year);
  }
  return years;
}

// Common organizations/employers
export const COMMON_ORGANIZATIONS = [
  'United Nations Development Programme (UNDP)',
  'United Nations Children\'s Fund (UNICEF)',
  'World Health Organization (WHO)',
  'World Food Programme (WFP)',
  'UN Women',
  'UNHCR',
  'UNESCO',
  'FAO',
  'ILO',
  'UNEP',
  'World Bank',
  'International Monetary Fund (IMF)',
  'African Development Bank (AfDB)',
  'Asian Development Bank (ADB)',
  'Inter-American Development Bank (IDB)',
  'European Bank for Reconstruction and Development (EBRD)',
  'European Investment Bank (EIB)',
  'USAID',
  'DFID (UK Aid)',
  'GIZ (Germany)',
  'AFD (France)',
  'JICA (Japan)',
  'SIDA (Sweden)',
  'DANIDA (Denmark)',
  'NORAD (Norway)',
  'Swiss Development Cooperation',
  'Global Fund',
  'GAVI Alliance',
  'Bill & Melinda Gates Foundation',
  'Open Society Foundations',
  'Save the Children',
  'Oxfam',
  'CARE International',
  'World Vision',
  'Plan International',
  'Médecins Sans Frontières (MSF)',
  'International Rescue Committee (IRC)',
  'Norwegian Refugee Council (NRC)',
  'Catholic Relief Services (CRS)',
  'Action Against Hunger',
  'Mercy Corps',
  'International Committee of the Red Cross (ICRC)',
  'Red Cross / Red Crescent',
  'Other',
];

// Months for date selection
export const MONTHS = [
  { value: '01', label: 'January' },
  { value: '02', label: 'February' },
  { value: '03', label: 'March' },
  { value: '04', label: 'April' },
  { value: '05', label: 'May' },
  { value: '06', label: 'June' },
  { value: '07', label: 'July' },
  { value: '08', label: 'August' },
  { value: '09', label: 'September' },
  { value: '10', label: 'October' },
  { value: '11', label: 'November' },
  { value: '12', label: 'December' },
];

// Months translations
export const MONTHS_I18N = {
  en: [
    { value: '01', label: 'January' },
    { value: '02', label: 'February' },
    { value: '03', label: 'March' },
    { value: '04', label: 'April' },
    { value: '05', label: 'May' },
    { value: '06', label: 'June' },
    { value: '07', label: 'July' },
    { value: '08', label: 'August' },
    { value: '09', label: 'September' },
    { value: '10', label: 'October' },
    { value: '11', label: 'November' },
    { value: '12', label: 'December' },
  ],
  fr: [
    { value: '01', label: 'Janvier' },
    { value: '02', label: 'Février' },
    { value: '03', label: 'Mars' },
    { value: '04', label: 'Avril' },
    { value: '05', label: 'Mai' },
    { value: '06', label: 'Juin' },
    { value: '07', label: 'Juillet' },
    { value: '08', label: 'Août' },
    { value: '09', label: 'Septembre' },
    { value: '10', label: 'Octobre' },
    { value: '11', label: 'Novembre' },
    { value: '12', label: 'Décembre' },
  ],
  es: [
    { value: '01', label: 'Enero' },
    { value: '02', label: 'Febrero' },
    { value: '03', label: 'Marzo' },
    { value: '04', label: 'Abril' },
    { value: '05', label: 'Mayo' },
    { value: '06', label: 'Junio' },
    { value: '07', label: 'Julio' },
    { value: '08', label: 'Agosto' },
    { value: '09', label: 'Septiembre' },
    { value: '10', label: 'Octubre' },
    { value: '11', label: 'Noviembre' },
    { value: '12', label: 'Diciembre' },
  ],
};