import React, { createContext, useContext, useState, ReactNode } from 'react';
import {
  ProjectListDTO,
  ProjectStatusEnum,
  ProjectPriorityEnum,
  ProjectTypeEnum,
  ProjectSectorEnum,
  RegionEnum,
  TaskDTO,
  CollaborationDTO,
  ProjectTemplateDTO,
  ProjectKPIsDTO,
} from '../types/project.dto';
import { projectService } from '../services/projectService';

// Extended type pour l'usage interne avec champs additionnels
interface ProjectListDTOInternal extends ProjectListDTO {
  name: string;
  managerName?: string;
}

interface ProjectsContextType {
  projects: ProjectListDTOInternal[];
  addProject: (project: ProjectListDTOInternal) => void;
  updateProject: (id: string, project: Partial<ProjectListDTOInternal>) => void;
  deleteProject: (id: string) => void;
  getProjectById: (id: string) => ProjectListDTOInternal | undefined;
  tasks: TaskDTO[];
  addTask: (task: TaskDTO) => void;
  collaborations: CollaborationDTO[];
  addCollaboration: (collaboration: CollaborationDTO) => void;
  templates: ProjectTemplateDTO[];
  kpis: ProjectKPIsDTO | null;
}

const ProjectsContext = createContext<ProjectsContextType | undefined>(undefined);

// Mock Data Initial
/*
const initialMockProjects: ProjectListDTOInternal[] = [
  {
    id: '1',
    referenceCode: 'PROJ-2024-001',
    code: 'PROJ-2024-001',
    title: 'EDUCATION Development Project 1',
    name: 'EDUCATION Development Project 1',
    managerName: 'Sarah Johnson',
    description: 'Construction and renovation of primary schools in rural communities to improve access to quality education.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.HIGH,
    type: ProjectTypeEnum.INFRASTRUCTURE,
    donor: { id: 1, name: 'World Bank', shortName: 'WB', type: 'MULTILATERAL' },
    fundingType: 'GRANT',
    budget: 2500000,
    currency: 'USD',
    country: { id: 1, name: 'Kenya', code: 'KE', iso3: 'KEN' },
    city: { id: 1, name: 'Nairobi' },
    startDate: '2023-06-01',
    endDate: '2025-05-31',
    isValidatedByOrg: true,
    validatedAt: '2023-05-15T10:00:00Z',
    validatedByOrg: { id: 1, name: 'Assortis Tech' },
    estimatedShare: 100,
    mainSector: { id: 1, name: 'Education', code: 'EDU' },
    sector: ProjectSectorEnum.EDUCATION,
    subsectors: ['PRIMARY_EDUCATION', 'INFRASTRUCTURE'],
    objectives: { main: 'Improve access to quality education' },
    deliverables: { d1: '10 primary schools renovated' },
    updatedAt: '2024-02-20T14:30:00Z',
    region: RegionEnum.AFRICA_EAST,
    teamSize: 45,
    tasksCompleted: 128,
    totalTasks: 172,
    scope: 'National',
    source: 'Tender Board',
  },
  {
    id: '2',
    referenceCode: 'PROJ-2024-002',
    code: 'PROJ-2024-002',
    title: 'HEALTH Development Project 2',
    name: 'HEALTH Development Project 2',
    managerName: 'Dr. Amina Hassan',
    description: 'Comprehensive program to reduce maternal and child mortality through improved healthcare services and community awareness.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.URGENT,
    type: ProjectTypeEnum.DEVELOPMENT,
    donor: { id: 2, name: 'UNICEF', shortName: 'UNICEF', type: 'UN_AGENCY' },
    fundingType: 'GRANT',
    budget: 3200000,
    currency: 'USD',
    country: { id: 2, name: 'Ethiopia', code: 'ET', iso3: 'ETH' },
    city: { id: 2, name: 'Addis Ababa' },
    startDate: '2023-03-01',
    endDate: '2025-02-28',
    isValidatedByOrg: true,
    validatedAt: '2023-01-20T09:00:00Z',
    validatedByOrg: { id: 1, name: 'Assortis Tech' },
    estimatedShare: 100,
    mainSector: { id: 2, name: 'Health', code: 'HEA' },
    sector: ProjectSectorEnum.HEALTH,
    subsectors: ['MATERNAL_CHILD_HEALTH', 'PRIMARY_HEALTHCARE'],
    objectives: { main: 'Reduce maternal and child mortality' },
    deliverables: { d1: 'Healthcare services improved' },
    updatedAt: '2024-02-24T11:20:00Z',
    region: RegionEnum.AFRICA_EAST,
    teamSize: 62,
    tasksCompleted: 156,
    totalTasks: 198,
    scope: 'Regional',
    source: 'UN Portal',
  },
  {
    id: '3',
    referenceCode: 'PROJ-2024-003',
    code: 'PROJ-2024-003',
    title: 'AGRICULTURE Development Project 3',
    name: 'AGRICULTURE Development Project 3',
    managerName: 'Pierre Dubois',
    description: 'Training program for smallholder farmers on sustainable agricultural practices and climate-smart technologies.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.MEDIUM,
    type: ProjectTypeEnum.CAPACITY_BUILDING,
    donor: { id: 3, name: 'FAO', shortName: 'FAO', type: 'UN_AGENCY' },
    fundingType: 'GRANT',
    budget: 850000,
    currency: 'USD',
    country: { id: 3, name: 'Senegal', code: 'SN', iso3: 'SEN' },
    city: { id: 3, name: 'Dakar' },
    startDate: '2024-01-01',
    endDate: '2025-12-31',
    isValidatedByOrg: true,
    validatedAt: '2023-11-10T08:30:00Z',
    validatedByOrg: { id: 1, name: 'Assortis Tech' },
    estimatedShare: 100,
    mainSector: { id: 3, name: 'Agriculture', code: 'AGR' },
    sector: ProjectSectorEnum.AGRICULTURE,
    subsectors: ['RURAL_DEVELOPMENT', 'FOOD_SECURITY'],
    objectives: { main: 'Promote sustainable agricultural practices' },
    deliverables: { d1: 'Farmer training completed' },
    updatedAt: '2024-02-22T16:45:00Z',
    region: RegionEnum.AFRICA_WEST,
    teamSize: 18,
    tasksCompleted: 42,
    totalTasks: 96,
    scope: 'Local',
    source: 'FAO website',
  },
  {
    id: '4',
    referenceCode: 'PROJ-2023-042',
    code: 'PROJ-2023-042',
    title: 'INFRASTRUCTURE Development Project 4',
    name: 'INFRASTRUCTURE Development Project 4',
    managerName: 'Michael Brown',
    description: 'Installation of clean water systems and sanitation facilities in underserved communities.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.HIGH,
    type: ProjectTypeEnum.INFRASTRUCTURE,
    donor: { id: 4, name: 'African Development Bank', shortName: 'AfDB', type: 'MULTILATERAL' },
    fundingType: 'LOAN',
    budget: 4500000,
    currency: 'USD',
    country: { id: 4, name: 'Tanzania', code: 'TZ', iso3: 'TZA' },
    city: { id: 4, name: 'Dodoma' },
    startDate: '2023-07-01',
    endDate: '2025-06-30',
    isValidatedByOrg: true,
    validatedAt: '2023-05-10T14:00:00Z',
    validatedByOrg: { id: 1, name: 'Assortis Tech' },
    estimatedShare: 100,
    mainSector: { id: 4, name: 'Water & Sanitation', code: 'WASH' },
    sector: ProjectSectorEnum.WATER_SANITATION,
    subsectors: ['WATER_SUPPLY', 'SANITATION', 'WASH'],
    objectives: { main: 'Install clean water systems' },
    deliverables: { d1: 'Water systems installed' },
    updatedAt: '2024-02-23T10:15:00Z',
    region: RegionEnum.AFRICA_EAST,
    teamSize: 54,
    tasksCompleted: 184,
    totalTasks: 245,
    scope: 'National',
    source: 'AfDB portal',
  },
  {
    id: '5',
    referenceCode: 'PROJ-2024-015',
    code: 'PROJ-2024-015',
    title: 'ENVIRONMENT Development Project 5',
    name: 'ENVIRONMENT Development Project 5',
    managerName: 'Clara Nguyen',
    description: 'Development and implementation of climate change adaptation strategies for vulnerable coastal communities.',
    status: ProjectStatusEnum.PLANNING,
    priority: ProjectPriorityEnum.MEDIUM,
    type: ProjectTypeEnum.RESEARCH,
    donor: { id: 5, name: 'UNDP', shortName: 'UNDP', type: 'UN_AGENCY' },
    fundingType: 'GRANT',
    budget: 1200000,
    currency: 'USD',
    country: { id: 5, name: 'Bangladesh', code: 'BD', iso3: 'BGD' },
    city: { id: 5, name: 'Dhaka' },
    startDate: '2024-04-01',
    endDate: '2026-03-31',
    isValidatedByOrg: true,
    validatedAt: '2024-02-01T12:00:00Z',
    validatedByOrg: { id: 1, name: 'Assortis Tech' },
    estimatedShare: 100,
    mainSector: { id: 5, name: 'Environment', code: 'ENV' },
    sector: ProjectSectorEnum.ENVIRONMENT,
    subsectors: ['CLIMATE_CHANGE', 'SUSTAINABLE_DEVELOPMENT'],
    objectives: { main: 'Develop climate adaptation strategies' },
    deliverables: { d1: 'Adaptation strategy report' },
    updatedAt: '2024-02-24T09:30:00Z',
    region: RegionEnum.ASIA_PACIFIC,
    teamSize: 22,
    tasksCompleted: 8,
    totalTasks: 78,
    scope: 'Coastal',
    source: 'UNDP news',
  },
  {
    id: '6',
    referenceCode: 'PROJ-2023-028',
    code: 'PROJ-2023-028',
    title: 'ENERGY Development Project 6',
    name: 'ENERGY Development Project 6',
    managerName: 'Youssef El Amrani',
    description: 'Installation of solar power systems in rural areas to improve energy access and reduce carbon emissions.',
    status: ProjectStatusEnum.COMPLETED,
    priority: ProjectPriorityEnum.MEDIUM,
    type: ProjectTypeEnum.INFRASTRUCTURE,
    donor: { id: 4, name: 'African Development Bank', shortName: 'AfDB', type: 'MULTILATERAL' },
    fundingType: 'LOAN',
    budget: 5600000,
    currency: 'USD',
    country: { id: 6, name: 'Morocco', code: 'MA', iso3: 'MAR' },
    city: { id: 6, name: 'Rabat' },
    startDate: '2022-01-01',
    endDate: '2024-01-31',
    isValidatedByOrg: true,
    validatedAt: '2021-10-15T11:00:00Z',
    validatedByOrg: { id: 2, name: 'Morocco Energy' },
    estimatedShare: 100,
    mainSector: { id: 6, name: 'Energy', code: 'ENE' },
    sector: ProjectSectorEnum.ENERGY,
    subsectors: ['RENEWABLE_ENERGY', 'SOLAR'],
    objectives: { main: 'Install solar power systems' },
    deliverables: { d1: 'Solar units installed' },
    updatedAt: '2024-02-05T15:00:00Z',
    region: RegionEnum.AFRICA_NORTH,
    teamSize: 78,
    tasksCompleted: 234,
    totalTasks: 234,
    scope: 'Rural',
    source: 'Gov Portal Morocco',
  },
  {
    id: '7',
    referenceCode: 'PROJ-2024-007',
    code: 'PROJ-2024-007',
    title: 'GOVERNANCE Development Project 7',
    name: 'GOVERNANCE Development Project 7',
    managerName: 'Fatima Al-Rashid',
    description: 'Strengthening public institutions and democratic governance frameworks in post-conflict regions.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.HIGH,
    type: ProjectTypeEnum.DEVELOPMENT,
    donor: { id: 7, name: 'European Commission', shortName: 'EC', type: 'BILATERAL' },
    fundingType: 'GRANT',
    budget: 1800000,
    currency: 'EUR',
    country: { id: 7, name: 'Mali', code: 'ML', iso3: 'MLI' },
    city: { id: 7, name: 'Bamako' },
    startDate: '2024-02-01',
    endDate: '2026-01-31',
    isValidatedByOrg: true,
    validatedAt: '2024-01-10T10:00:00Z',
    validatedByOrg: { id: 1, name: 'Assortis Tech' },
    estimatedShare: 100,
    mainSector: { id: 7, name: 'Governance', code: 'GOV' },
    sector: ProjectSectorEnum.GOVERNANCE,
    subsectors: ['PUBLIC_ADMINISTRATION', 'JUSTICE_REFORM'],
    objectives: { main: 'Strengthen public institutions' },
    deliverables: { d1: 'Institutional framework report' },
    updatedAt: '2024-03-01T14:00:00Z',
    region: RegionEnum.AFRICA_WEST,
    teamSize: 30,
    tasksCompleted: 34,
    totalTasks: 112,
    scope: 'Institutional',
    source: 'EC Tender',
  },
  {
    id: '8',
    referenceCode: 'PROJ-2024-008',
    code: 'PROJ-2024-008',
    title: 'GENDER Development Project 8',
    name: 'GENDER Development Project 8',
    managerName: 'Ingrid Larssen',
    description: 'Promoting gender equality and women economic empowerment through entrepreneurship training and access to finance.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.MEDIUM,
    type: ProjectTypeEnum.CAPACITY_BUILDING,
    donor: { id: 8, name: 'UN Women', shortName: 'UNW', type: 'UN_AGENCY' },
    fundingType: 'GRANT',
    budget: 950000,
    currency: 'USD',
    country: { id: 8, name: 'Uganda', code: 'UG', iso3: 'UGA' },
    city: { id: 8, name: 'Kampala' },
    startDate: '2024-03-01',
    endDate: '2025-08-31',
    isValidatedByOrg: true,
    validatedAt: '2024-01-25T13:00:00Z',
    validatedByOrg: { id: 2, name: 'Uganda Gender Org' },
    estimatedShare: 100,
    mainSector: { id: 8, name: 'Gender', code: 'GEN' },
    sector: ProjectSectorEnum.GENDER,
    subsectors: ['WOMENS_EMPOWERMENT', 'ECONOMIC_EMPOWERMENT'],
    objectives: { main: 'Promote gender equality' },
    deliverables: { d1: 'Training modules' },
    updatedAt: '2024-03-05T09:00:00Z',
    region: RegionEnum.AFRICA_EAST,
    teamSize: 14,
    tasksCompleted: 18,
    totalTasks: 80,
    scope: 'National',
    source: 'UN Women portal',
  },
  {
    id: '9',
    referenceCode: 'PROJ-2024-009',
    code: 'PROJ-2024-009',
    title: 'DIGITAL Development Project 9',
    name: 'DIGITAL Development Project 9',
    managerName: 'Rajesh Patel',
    description: 'Expanding digital infrastructure and ICT skills to bridge the digital divide in underserved urban districts.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.HIGH,
    type: ProjectTypeEnum.DEVELOPMENT,
    donor: { id: 9, name: 'USAID', shortName: 'USAID', type: 'BILATERAL' },
    fundingType: 'GRANT',
    budget: 2100000,
    currency: 'USD',
    country: { id: 9, name: 'India', code: 'IN', iso3: 'IND' },
    city: { id: 9, name: 'New Delhi' },
    startDate: '2024-01-15',
    endDate: '2025-07-14',
    isValidatedByOrg: true,
    validatedAt: '2023-12-01T15:00:00Z',
    validatedByOrg: { id: 1, name: 'Assortis Tech' },
    estimatedShare: 100,
    mainSector: { id: 4, name: 'Infrastructure', code: 'INF' },
    sector: ProjectSectorEnum.INFRASTRUCTURE,
    subsectors: ['TELECOMMUNICATIONS', 'URBAN_PLANNING'],
    objectives: { main: 'Bridge the digital divide' },
    deliverables: { d1: 'Digital infrastructure map' },
    updatedAt: '2024-03-10T12:00:00Z',
    region: RegionEnum.ASIA_PACIFIC,
    teamSize: 26,
    tasksCompleted: 64,
    totalTasks: 140,
    scope: 'Urban',
    source: 'USAID portal',
  },
  {
    id: '10',
    referenceCode: 'PROJ-2023-010',
    code: 'PROJ-2023-010',
    title: 'NUTRITION Development Project 10',
    name: 'NUTRITION Development Project 10',
    managerName: 'Marie Leclerc',
    description: 'Combatting malnutrition and food insecurity through community-based nutrition programs and school feeding initiatives.',
    status: ProjectStatusEnum.ON_HOLD,
    priority: ProjectPriorityEnum.URGENT,
    type: ProjectTypeEnum.DEVELOPMENT,
    donor: { id: 10, name: 'World Food Programme', shortName: 'WFP', type: 'UN_AGENCY' },
    fundingType: 'GRANT',
    budget: 2800000,
    currency: 'EUR',
    country: { id: 10, name: 'Niger', code: 'NE', iso3: 'NER' },
    city: { id: 10, name: 'Niamey' },
    startDate: '2023-09-01',
    endDate: '2025-08-31',
    isValidatedByOrg: true,
    validatedAt: '2023-07-15T09:00:00Z',
    validatedByOrg: { id: 2, name: 'Niger Health' },
    estimatedShare: 100,
    mainSector: { id: 2, name: 'Health', code: 'HEA' },
    sector: ProjectSectorEnum.HEALTH,
    subsectors: ['NUTRITION', 'HEALTH_SYSTEMS'],
    objectives: { main: 'Combat malnutrition' },
    deliverables: { d1: 'Feeding program report' },
    updatedAt: '2024-02-28T16:00:00Z',
    region: RegionEnum.AFRICA_WEST,
    teamSize: 48,
    tasksCompleted: 98,
    totalTasks: 196,
    scope: 'National',
    source: 'WFP portal',
  },
  {
    id: '11',
    referenceCode: 'PROJ-2024-011',
    code: 'PROJ-2024-011',
    title: 'TRANSPORT Development Project 11',
    name: 'TRANSPORT Development Project 11',
    managerName: 'Carlos Mendoza',
    description: 'Rehabilitation of rural road networks to improve market access and reduce post-harvest losses for farming communities.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.HIGH,
    type: ProjectTypeEnum.INFRASTRUCTURE,
    donor: { id: 11, name: 'Inter-American Development Bank', shortName: 'IDB', type: 'MULTILATERAL' },
    fundingType: 'LOAN',
    budget: 7200000,
    currency: 'USD',
    country: { id: 11, name: 'Peru', code: 'PE', iso3: 'PER' },
    city: { id: 11, name: 'Lima' },
    startDate: '2024-03-01',
    endDate: '2027-02-28',
    isValidatedByOrg: true,
    validatedAt: '2024-01-05T10:00:00Z',
    validatedByOrg: { id: 1, name: 'Assortis Tech' },
    estimatedShare: 100,
    mainSector: { id: 4, name: 'Infrastructure', code: 'INF' },
    sector: ProjectSectorEnum.INFRASTRUCTURE,
    subsectors: ['ROADS_TRANSPORT', 'BUILDINGS'],
    objectives: { main: 'Rehabilitate rural road networks' },
    deliverables: { d1: 'Road map completed' },
    updatedAt: '2024-03-12T14:00:00Z',
    region: RegionEnum.SOUTH_AMERICA,
    teamSize: 95,
    tasksCompleted: 22,
    totalTasks: 160,
    scope: 'Regional',
    source: 'IDB portal',
  },
  {
    id: '12',
    referenceCode: 'PROJ-2022-012',
    code: 'PROJ-2022-012',
    title: 'FINANCE Development Project 12',
    name: 'FINANCE Development Project 12',
    managerName: 'Aisha Kamara',
    description: 'Improving access to microfinance and financial literacy for small business owners and rural entrepreneurs.',
    status: ProjectStatusEnum.COMPLETED,
    priority: ProjectPriorityEnum.MEDIUM,
    type: ProjectTypeEnum.CAPACITY_BUILDING,
    donor: { id: 12, name: 'AFD', shortName: 'AFD', type: 'BILATERAL' },
    fundingType: 'GRANT',
    budget: 1600000,
    currency: 'USD',
    country: { id: 12, name: 'Ghana', code: 'GH', iso3: 'GHA' },
    city: { id: 12, name: 'Accra' },
    startDate: '2022-06-01',
    endDate: '2024-05-31',
    isValidatedByOrg: true,
    validatedAt: '2022-04-10T11:00:00Z',
    validatedByOrg: { id: 2, name: 'Ghana Finance' },
    estimatedShare: 100,
    mainSector: { id: 7, name: 'Governance', code: 'GOV' },
    sector: ProjectSectorEnum.GOVERNANCE,
    subsectors: ['CIVIL_SOCIETY', 'ANTI_CORRUPTION'],
    objectives: { main: 'Improve access to microfinance' },
    deliverables: { d1: 'Microfinance report' },
    updatedAt: '2024-06-01T15:00:00Z',
    region: RegionEnum.AFRICA_WEST,
    teamSize: 20,
    tasksCompleted: 132,
    totalTasks: 132,
    scope: 'National',
    source: 'AFD website',
  },
];
*/

// Mock Tasks Initial
const initialMockTasks: TaskDTO[] = [
  {
    id: 1,
    projectId: 1,
    title: 'Complete site survey for new school building',
    description: 'Conduct detailed site survey and soil testing for the new primary school construction in Kisumu region.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assignedTo: { names: ['John Doe', 'Jane Smith'] },
    startDate: '2024-03-01',
    dueDate: '2024-03-15',
    tags: { categories: ['survey', 'infrastructure'] },
    taskCode: 'TSK-001',
    isMilestone: false,
  },
  {
    id: 2,
    projectId: 1,
    title: 'Finalize architectural plans',
    description: 'Complete architectural drawings for 3 school buildings and get approval from Ministry of Education.',
    status: 'TODO',
    priority: 'URGENT',
    assignedTo: { names: ['Architect Team'] },
    startDate: '2024-03-05',
    dueDate: '2024-03-10',
    tags: { categories: ['design', 'planning'] },
    taskCode: 'TSK-002',
    isMilestone: true,
  },
  {
    id: 3,
    projectId: 2,
    title: 'Conduct community health training',
    description: 'Train 50 community health workers on maternal care and nutrition best practices.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assignedTo: { names: ['Health Team', 'Dr. Amina Hassan'] },
    startDate: '2024-03-10',
    dueDate: '2024-03-20',
    tags: { categories: ['training', 'health'] },
    taskCode: 'TSK-003',
    isMilestone: false,
  },
  {
    id: 4,
    projectId: 2,
    title: 'Develop training materials',
    description: 'Create comprehensive training modules on sustainable farming techniques and climate-smart agriculture.',
    status: 'COMPLETED',
    priority: 'MEDIUM',
    assignedTo: { names: ['Training Department'] },
    startDate: '2024-02-01',
    dueDate: '2024-02-28',
    tags: { categories: ['materials', 'agriculture'] },
    taskCode: 'TSK-004',
    isMilestone: false,
  },
  {
    id: 5,
    projectId: 4,
    title: 'Install water filtration systems',
    description: 'Install and test 12 water filtration units in selected communities.',
    status: 'IN_PROGRESS',
    priority: 'URGENT',
    assignedTo: { names: ['Engineering Team', 'Michael Brown'] },
    startDate: '2024-03-01',
    dueDate: '2024-03-25',
    tags: { categories: ['installation', 'water'] },
    taskCode: 'TSK-005',
    isMilestone: false,
  },
  {
    id: 6,
    projectId: 1,
    title: 'Procurement of construction materials',
    description: 'Source and procure cement, steel, and other construction materials according to approved specifications.',
    status: 'TODO',
    priority: 'HIGH',
    assignedTo: { names: ['Procurement Team'] },
    startDate: '2024-03-15',
    dueDate: '2024-03-30',
    tags: { categories: ['procurement', 'materials'] },
    taskCode: 'TSK-006',
    isMilestone: false,
  },
  {
    id: 7,
    projectId: 2,
    title: 'Monthly health monitoring report',
    description: 'Compile and submit monthly monitoring report on maternal and child health indicators.',
    status: 'REVIEW',
    priority: 'MEDIUM',
    assignedTo: { names: ['M&E Team'] },
    startDate: '2024-03-01',
    dueDate: '2024-03-08',
    tags: { categories: ['monitoring', 'reporting'] },
    taskCode: 'TSK-007',
    isMilestone: false,
  },
  {
    id: 8,
    projectId: 3,
    title: 'Organize farmer field visits',
    description: 'Coordinate field visits to demonstration farms for 200 smallholder farmers.',
    status: 'TODO',
    priority: 'MEDIUM',
    assignedTo: { names: ['Field Officers'] },
    startDate: '2024-03-20',
    dueDate: '2024-04-10',
    tags: { categories: ['fieldwork', 'training'] },
    taskCode: 'TSK-008',
    isMilestone: false,
  },
  {
    id: 9,
    projectId: 4,
    title: 'Community awareness campaign',
    description: 'Launch community awareness campaign on water conservation and sanitation practices.',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    assignedTo: { names: ['Communications Team', 'Community Mobilizers'] },
    startDate: '2024-02-15',
    dueDate: '2024-03-31',
    tags: { categories: ['awareness', 'community'] },
    taskCode: 'TSK-009',
    isMilestone: false,
  },
  {
    id: 10,
    projectId: 5,
    title: 'Baseline vulnerability assessment',
    description: 'Conduct baseline assessment of climate vulnerabilities in target coastal communities.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assignedTo: { names: ['Research Team'] },
    startDate: '2024-02-01',
    dueDate: '2024-03-15',
    tags: { categories: ['research', 'assessment'] },
    taskCode: 'TSK-010',
  },
];

// Mock Collaborations Initial
const initialMockCollaborations: CollaborationDTO[] = [
  {
    id: 'c1',
    projectId: '1',
    projectTitle: 'EDUCATION Hajer Project 1',
    partnerOrganization: 'Local NGO Consortium',
    type: 'IMPLEMENTATION',
    status: 'ACTIVE',
    startDate: '2023-06-01',
    contribution: 'Community mobilization, local project management, and stakeholder engagement.',
  },
  {
    id: 'c2',
    projectId: '2',
    projectTitle: 'HEALTH Development Project 2',
    partnerOrganization: 'Farmers Association of Senegal',
    type: 'TECHNICAL',
    status: 'ACTIVE',
    startDate: '2024-01-01',
    contribution: 'Training delivery, farmer outreach, and on-ground technical support.',
  },
  {
    id: 'c3',
    projectId: '3',
    projectTitle: 'AGRICULTURE Development Project 3',
    partnerOrganization: 'World Health Organization (WHO)',
    type: 'TECHNICAL',
    status: 'ACTIVE',
    startDate: '2023-03-01',
    contribution: 'Technical guidance on health protocols and capacity building of health workers.',
  },
  {
    id: 'c4',
    projectId: '1',
    projectTitle: 'EDUCATION Development Project 1',
    partnerOrganization: 'Ministry of Education Kenya',
    type: 'IMPLEMENTATION',
    status: 'ACTIVE',
    startDate: '2023-06-01',
    contribution: 'Regulatory approvals, curriculum development, and teacher training coordination.',
  },
  {
    id: 'c5',
    projectId: '4',
    projectTitle: 'INFRASTRUCTURE Development Project 4',
    partnerOrganization: 'WaterAid International',
    type: 'TECHNICAL',
    status: 'ACTIVE',
    startDate: '2023-07-01',
    contribution: 'Technical expertise on water systems design and community WASH training.',
  },
  {
    id: 'c6',
    projectId: '4',
    projectTitle: 'INFRASTRUCTURE Development Project 4',
    partnerOrganization: 'Government of Tanzania - Water Ministry',
    type: 'IMPLEMENTATION',
    status: 'ACTIVE',
    startDate: '2023-07-01',
    contribution: 'Policy coordination, land access facilitation, and sustainability planning.',
  },
  {
    id: 'c7',
    projectId: '2',
    projectTitle: 'HEALTH Development Project 2',
    partnerOrganization: 'Ministry of Agriculture Senegal',
    type: 'ADVISORY',
    status: 'ACTIVE',
    startDate: '2024-01-01',
    contribution: 'Policy guidance, extension services coordination, and research collaboration.',
  },
  {
    id: 'c8',
    projectId: '5',
    projectTitle: 'ENVIRONMENT Development Project 5',
    partnerOrganization: 'Local Research Institutions Bangladesh',
    type: 'TECHNICAL',
    status: 'ACTIVE',
    startDate: '2024-04-01',
    contribution: 'Climate data analysis, vulnerability assessments, and adaptation strategy development.',
  },
  {
    id: 'c9',
    projectId: '3',
    projectTitle: 'AGRICULTURE Development Project 3',
    partnerOrganization: 'Ministry of Health Ethiopia',
    type: 'IMPLEMENTATION',
    status: 'ACTIVE',
    startDate: '2023-03-01',
    contribution: 'Healthcare facilities coordination, medical supplies procurement, and health workforce management.',
  },
  {
    id: 'c10',
    projectId: '5',
    projectTitle: 'ENVIRONMENT Development Project 5',
    partnerOrganization: 'Government of Bangladesh - Environment Ministry',
    type: 'FUNDING',
    status: 'PENDING',
    startDate: '2024-04-01',
    contribution: 'Co-financing agreement for adaptation infrastructure and community resilience programs.',
  },
];

// Mock Templates Initial
const initialMockTemplates: ProjectTemplateDTO[] = [
  {
    id: 'tmp1',
    name: 'Education Infrastructure Standard',
    description: 'Standard template for school construction and renovation projects',
    sector: ProjectSectorEnum.EDUCATION,
    type: ProjectTypeEnum.INFRASTRUCTURE,
    estimatedDuration: 18,
    estimatedBudget: 2000000,
    usageCount: 24,
    rating: 4.8,
    createdBy: 'World Bank',
    createdDate: '2022-05-10',
  },
  {
    id: 'tmp2',
    name: 'Health System Strengthening',
    description: 'Comprehensive template for health system improvement projects',
    sector: ProjectSectorEnum.HEALTH,
    type: ProjectTypeEnum.DEVELOPMENT,
    estimatedDuration: 24,
    estimatedBudget: 3000000,
    usageCount: 18,
    rating: 4.6,
    createdBy: 'WHO',
    createdDate: '2022-08-15',
  },
  {
    id: 'tmp3',
    name: 'Agricultural Capacity Building',
    description: 'Farmer training and sustainable agriculture promotion template',
    sector: ProjectSectorEnum.AGRICULTURE,
    type: ProjectTypeEnum.CAPACITY_BUILDING,
    estimatedDuration: 18,
    estimatedBudget: 850000,
    usageCount: 32,
    rating: 4.7,
    createdBy: 'FAO',
    createdDate: '2022-03-20',
  },
  {
    id: 'tmp4',
    name: 'WASH Infrastructure Development',
    description: 'Water supply and sanitation infrastructure projects',
    sector: ProjectSectorEnum.WATER_SANITATION,
    type: ProjectTypeEnum.INFRASTRUCTURE,
    estimatedDuration: 24,
    estimatedBudget: 4000000,
    usageCount: 15,
    rating: 4.5,
    createdBy: 'UNICEF',
    createdDate: '2022-06-30',
  },
];

export const ProjectsProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [projects, setProjects] = React.useState<ProjectListDTOInternal[]>([]);
  const [tasks, setTasks] = useState<TaskDTO[]>(initialMockTasks);
  const [collaborations, setCollaborations] = useState<CollaborationDTO[]>(initialMockCollaborations);
  const [templates, setTemplates] = useState<ProjectTemplateDTO[]>(initialMockTemplates);
  const [kpis, setKpis] = useState<ProjectKPIsDTO | null>(null);

React.useEffect(() => {
  const fetchData = async () => {
    try {
      const [projectsResult, kpisResult] = await Promise.all([
        projectService.getAllProjects(),
        projectService.getKPIs()
      ]);
      const projectsData = (projectsResult as any).data || (Array.isArray(projectsResult) ? projectsResult : []);
      setProjects(projectsData as ProjectListDTOInternal[]);
      setKpis(kpisResult as ProjectKPIsDTO);
    } catch (error) {
      console.error("Error fetching data:", error);
    }
  };

  fetchData();
}, []);

  const addProject = (project: ProjectListDTOInternal) => {
    setProjects((prev) => [project, ...prev]);
  };

  const updateProject = (id: string, updatedProject: Partial<ProjectListDTOInternal>) => {
    setProjects((prev) =>
      prev.map((project) =>
        project.id === id ? { ...project, ...updatedProject, updatedAt: new Date().toISOString() } : project
      )
    );
  };

  const deleteProject = (id: string) => {
    setProjects((prev) => prev.filter((project) => project.id !== id));
  };

  const getProjectById = (id: string) => {
    return projects.find((project) => project.id === id);
  };

  const addTask = (task: TaskDTO) => {
    setTasks((prev) => [task, ...prev]);
  };

  const addCollaboration = (collaboration: CollaborationDTO) => {
    setCollaborations((prev) => [collaboration, ...prev]);
  };

  return (
    <ProjectsContext.Provider
      value={{
        projects,
        addProject,
        updateProject,
        deleteProject,
        getProjectById,
        tasks,
        addTask,
        collaborations,
        addCollaboration,
        templates,
        kpis,
      }}
    >
      {children}
    </ProjectsContext.Provider>
  );
};

export const useProjectsContext = () => {
  const context = useContext(ProjectsContext);
  if (!context) {
    throw new Error('useProjectsContext must be used within a ProjectsProvider');
  }
  return context;
};