import React, { createContext, useContext, useState, ReactNode } from 'react';
import {
  ProjectListDTO,
  ProjectStatusEnum,
  ProjectPriorityEnum,
  ProjectTypeEnum,
  ProjectSectorEnum,
  RegionEnum,
  TaskDTO,
  CollaborationDTO,
  ProjectTemplateDTO,
} from '../types/project.dto';

// Extended type pour l'usage interne avec champs additionnels
interface ProjectListDTOInternal extends ProjectListDTO {
  name: string;
  managerName?: string;
}

interface ProjectsContextType {
  projects: ProjectListDTOInternal[];
  addProject: (project: ProjectListDTOInternal) => void;
  updateProject: (id: string, project: Partial<ProjectListDTOInternal>) => void;
  deleteProject: (id: string) => void;
  getProjectById: (id: string) => ProjectListDTOInternal | undefined;
  tasks: TaskDTO[];
  addTask: (task: TaskDTO) => void;
  collaborations: CollaborationDTO[];
  addCollaboration: (collaboration: CollaborationDTO) => void;
  templates: ProjectTemplateDTO[];
}

const ProjectsContext = createContext<ProjectsContextType | undefined>(undefined);

// Mock Data Initial
const initialMockProjects: ProjectListDTOInternal[] = [
  {
    id: '1',
    organizationId: 'org-1',
    code: 'PROJ-2024-001',
    title: 'EDUCATION Development Project 1',
    name: 'EDUCATION Development Project 1',
    managerName: 'Sarah Johnson',
    description: 'Construction and renovation of primary schools in rural communities to improve access to quality education.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.HIGH,
    type: ProjectTypeEnum.INFRASTRUCTURE,
    country: 'Kenya',
    region: RegionEnum.AFRICA_EAST,
    sector: ProjectSectorEnum.EDUCATION,
    subsectors: ['PRIMARY_EDUCATION', 'INFRASTRUCTURE'],
    budget: {
      total: 2500000,
      spent: 1850000,
      remaining: 650000,
      currency: 'USD',
    },
    timeline: {
      startDate: '2023-06-01',
      endDate: '2025-05-31',
      duration: 24,
      completionPercentage: 74,
    },
    leadOrganization: 'World Bank',
    partners: ['Ministry of Education Kenya', 'Local NGO Consortium'],
    teamSize: 45,
    tasksCompleted: 128,
    totalTasks: 172,
    createdDate: '2023-05-15',
    updatedDate: '2024-02-20',
  },
  {
    id: '2',
    organizationId: 'org-1',
    code: 'PROJ-2024-002',
    title: 'HEALTH Development Project 2',
    name: 'HEALTH Development Project 2',
    managerName: 'Dr. Amina Hassan',
    description: 'Comprehensive program to reduce maternal and child mortality through improved healthcare services and community awareness.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.URGENT,
    type: ProjectTypeEnum.DEVELOPMENT,
    country: 'Ethiopia',
    region: RegionEnum.AFRICA_EAST,
    sector: ProjectSectorEnum.HEALTH,
    subsectors: ['MATERNAL_CHILD_HEALTH', 'PRIMARY_HEALTHCARE'],
    budget: {
      total: 3200000,
      spent: 2100000,
      remaining: 1100000,
      currency: 'USD',
    },
    timeline: {
      startDate: '2023-03-01',
      endDate: '2025-02-28',
      duration: 24,
      completionPercentage: 66,
    },
    leadOrganization: 'UNICEF',
    partners: ['WHO', 'Ministry of Health Ethiopia'],
    teamSize: 62,
    tasksCompleted: 156,
    totalTasks: 198,
    createdDate: '2023-01-20',
    updatedDate: '2024-02-24',
  },
  {
    id: '3',
    organizationId: 'org-1',
    code: 'PROJ-2024-003',
    title: 'AGRICULTURE Development Project 3',
    name: 'AGRICULTURE Development Project 3',
    managerName: 'Pierre Dubois',
    description: 'Training program for smallholder farmers on sustainable agricultural practices and climate-smart technologies.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.MEDIUM,
    type: ProjectTypeEnum.CAPACITY_BUILDING,
    country: 'Senegal',
    region: RegionEnum.AFRICA_WEST,
    sector: ProjectSectorEnum.AGRICULTURE,
    subsectors: ['RURAL_DEVELOPMENT', 'FOOD_SECURITY'],
    budget: {
      total: 850000,
      spent: 420000,
      remaining: 430000,
      currency: 'USD',
    },
    timeline: {
      startDate: '2024-01-01',
      endDate: '2025-12-31',
      duration: 24,
      completionPercentage: 35,
    },
    leadOrganization: 'FAO',
    partners: ['Ministry of Agriculture Senegal', 'Farmers Association'],
    teamSize: 18,
    tasksCompleted: 42,
    totalTasks: 96,
    createdDate: '2023-11-10',
    updatedDate: '2024-02-22',
  },
  {
    id: '4',
    organizationId: 'org-1',
    code: 'PROJ-2023-042',
    title: 'INFRASTRUCTURE Development Project 4',
    name: 'INFRASTRUCTURE Development Project 4',
    managerName: 'Michael Brown',
    description: 'Installation of clean water systems and sanitation facilities in underserved communities.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.HIGH,
    type: ProjectTypeEnum.INFRASTRUCTURE,
    country: 'Tanzania',
    region: RegionEnum.AFRICA_EAST,
    sector: ProjectSectorEnum.WATER_SANITATION,
    subsectors: ['WATER_SUPPLY', 'SANITATION', 'WASH'],
    budget: {
      total: 4500000,
      spent: 3200000,
      remaining: 1300000,
      currency: 'USD',
    },
    timeline: {
      startDate: '2023-07-01',
      endDate: '2025-06-30',
      duration: 24,
      completionPercentage: 71,
    },
    leadOrganization: 'African Development Bank',
    partners: ['WaterAid', 'Government of Tanzania'],
    teamSize: 54,
    tasksCompleted: 184,
    totalTasks: 245,
    createdDate: '2023-05-10',
    updatedDate: '2024-02-23',
  },
  {
    id: '5',
    organizationId: 'org-1',
    code: 'PROJ-2024-015',
    title: 'ENVIRONMENT Development Project 5',
    name: 'ENVIRONMENT Development Project 5',
    managerName: 'Clara Nguyen',
    description: 'Development and implementation of climate change adaptation strategies for vulnerable coastal communities.',
    status: ProjectStatusEnum.PLANNING,
    priority: ProjectPriorityEnum.MEDIUM,
    type: ProjectTypeEnum.RESEARCH,
    country: 'Bangladesh',
    region: RegionEnum.ASIA_PACIFIC,
    sector: ProjectSectorEnum.ENVIRONMENT,
    subsectors: ['CLIMATE_CHANGE', 'SUSTAINABLE_DEVELOPMENT'],
    budget: {
      total: 1200000,
      spent: 150000,
      remaining: 1050000,
      currency: 'USD',
    },
    timeline: {
      startDate: '2024-04-01',
      endDate: '2026-03-31',
      duration: 24,
      completionPercentage: 12,
    },
    leadOrganization: 'UNDP',
    partners: ['Government of Bangladesh', 'Local Research Institutions'],
    teamSize: 22,
    tasksCompleted: 8,
    totalTasks: 78,
    createdDate: '2024-02-01',
    updatedDate: '2024-02-24',
  },
  {
    id: '6',
    organizationId: 'org-2',
    code: 'PROJ-2023-028',
    title: 'ENERGY Development Project 6',
    name: 'ENERGY Development Project 6',
    managerName: 'Youssef El Amrani',
    description: 'Installation of solar power systems in rural areas to improve energy access and reduce carbon emissions.',
    status: ProjectStatusEnum.COMPLETED,
    priority: ProjectPriorityEnum.MEDIUM,
    type: ProjectTypeEnum.INFRASTRUCTURE,
    country: 'Morocco',
    region: RegionEnum.AFRICA_NORTH,
    sector: ProjectSectorEnum.ENERGY,
    subsectors: ['RENEWABLE_ENERGY', 'SOLAR'],
    budget: {
      total: 5600000,
      spent: 5450000,
      remaining: 150000,
      currency: 'USD',
    },
    timeline: {
      startDate: '2022-01-01',
      endDate: '2024-01-31',
      duration: 25,
      completionPercentage: 100,
    },
    leadOrganization: 'African Development Bank',
    partners: ['Ministry of Energy Morocco', 'Renewable Energy Consortium'],
    teamSize: 78,
    tasksCompleted: 234,
    totalTasks: 234,
    createdDate: '2021-10-15',
    updatedDate: '2024-02-05',
  },
  {
    id: '7',
    organizationId: 'org-1',
    code: 'PROJ-2024-007',
    title: 'GOVERNANCE Development Project 7',
    name: 'GOVERNANCE Development Project 7',
    managerName: 'Fatima Al-Rashid',
    description: 'Strengthening public institutions and democratic governance frameworks in post-conflict regions.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.HIGH,
    type: ProjectTypeEnum.DEVELOPMENT,
    country: 'Mali',
    region: RegionEnum.AFRICA_WEST,
    sector: ProjectSectorEnum.GOVERNANCE,
    subsectors: ['PUBLIC_ADMINISTRATION', 'JUSTICE_REFORM'],
    budget: {
      total: 1800000,
      spent: 720000,
      remaining: 1080000,
      currency: 'EUR',
    },
    timeline: {
      startDate: '2024-02-01',
      endDate: '2026-01-31',
      duration: 24,
      completionPercentage: 28,
    },
    leadOrganization: 'European Commission',
    partners: ['UN Peacebuilding Office', 'Government of Mali'],
    teamSize: 30,
    tasksCompleted: 34,
    totalTasks: 112,
    createdDate: '2024-01-10',
    updatedDate: '2024-03-01',
  },
  {
    id: '8',
    organizationId: 'org-2',
    code: 'PROJ-2024-008',
    title: 'GENDER Development Project 8',
    name: 'GENDER Development Project 8',
    managerName: 'Ingrid Larssen',
    description: 'Promoting gender equality and women economic empowerment through entrepreneurship training and access to finance.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.MEDIUM,
    type: ProjectTypeEnum.CAPACITY_BUILDING,
    country: 'Uganda',
    region: RegionEnum.AFRICA_EAST,
    sector: ProjectSectorEnum.GENDER,
    subsectors: ['WOMENS_EMPOWERMENT', 'ECONOMIC_EMPOWERMENT'],
    budget: {
      total: 950000,
      spent: 310000,
      remaining: 640000,
      currency: 'USD',
    },
    timeline: {
      startDate: '2024-03-01',
      endDate: '2025-08-31',
      duration: 18,
      completionPercentage: 22,
    },
    leadOrganization: 'UN Women',
    partners: ['Ministry of Gender Uganda', 'Local Women Groups'],
    teamSize: 14,
    tasksCompleted: 18,
    totalTasks: 80,
    createdDate: '2024-01-25',
    updatedDate: '2024-03-05',
  },
  {
    id: '9',
    organizationId: 'org-1',
    code: 'PROJ-2024-009',
    title: 'DIGITAL Development Project 9',
    name: 'DIGITAL Development Project 9',
    managerName: 'Rajesh Patel',
    description: 'Expanding digital infrastructure and ICT skills to bridge the digital divide in underserved urban districts.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.HIGH,
    type: ProjectTypeEnum.DEVELOPMENT,
    country: 'India',
    region: RegionEnum.ASIA_PACIFIC,
    sector: ProjectSectorEnum.INFRASTRUCTURE,
    subsectors: ['TELECOMMUNICATIONS', 'URBAN_PLANNING'],
    budget: {
      total: 2100000,
      spent: 840000,
      remaining: 1260000,
      currency: 'USD',
    },
    timeline: {
      startDate: '2024-01-15',
      endDate: '2025-07-14',
      duration: 18,
      completionPercentage: 40,
    },
    leadOrganization: 'USAID',
    partners: ['Ministry of Electronics India', 'Tech4Dev NGO'],
    teamSize: 26,
    tasksCompleted: 64,
    totalTasks: 140,
    createdDate: '2023-12-01',
    updatedDate: '2024-03-10',
  },
  {
    id: '10',
    organizationId: 'org-2',
    code: 'PROJ-2023-010',
    title: 'NUTRITION Development Project 10',
    name: 'NUTRITION Development Project 10',
    managerName: 'Marie Leclerc',
    description: 'Combatting malnutrition and food insecurity through community-based nutrition programs and school feeding initiatives.',
    status: ProjectStatusEnum.ON_HOLD,
    priority: ProjectPriorityEnum.URGENT,
    type: ProjectTypeEnum.DEVELOPMENT,
    country: 'Niger',
    region: RegionEnum.AFRICA_WEST,
    sector: ProjectSectorEnum.HEALTH,
    subsectors: ['NUTRITION', 'HEALTH_SYSTEMS'],
    budget: {
      total: 2800000,
      spent: 1400000,
      remaining: 1400000,
      currency: 'EUR',
    },
    timeline: {
      startDate: '2023-09-01',
      endDate: '2025-08-31',
      duration: 24,
      completionPercentage: 50,
    },
    leadOrganization: 'World Food Programme',
    partners: ['UNICEF', 'Government of Niger', 'Action Against Hunger'],
    teamSize: 48,
    tasksCompleted: 98,
    totalTasks: 196,
    createdDate: '2023-07-15',
    updatedDate: '2024-02-28',
  },
  {
    id: '11',
    organizationId: 'org-1',
    code: 'PROJ-2024-011',
    title: 'TRANSPORT Development Project 11',
    name: 'TRANSPORT Development Project 11',
    managerName: 'Carlos Mendoza',
    description: 'Rehabilitation of rural road networks to improve market access and reduce post-harvest losses for farming communities.',
    status: ProjectStatusEnum.ACTIVE,
    priority: ProjectPriorityEnum.HIGH,
    type: ProjectTypeEnum.INFRASTRUCTURE,
    country: 'Peru',
    region: RegionEnum.SOUTH_AMERICA,
    sector: ProjectSectorEnum.INFRASTRUCTURE,
    subsectors: ['ROADS_TRANSPORT', 'BUILDINGS'],
    budget: {
      total: 7200000,
      spent: 2160000,
      remaining: 5040000,
      currency: 'USD',
    },
    timeline: {
      startDate: '2024-03-01',
      endDate: '2027-02-28',
      duration: 36,
      completionPercentage: 15,
    },
    leadOrganization: 'Inter-American Development Bank',
    partners: ['Ministry of Transport Peru', 'Regional Governments'],
    teamSize: 95,
    tasksCompleted: 22,
    totalTasks: 160,
    createdDate: '2024-01-05',
    updatedDate: '2024-03-12',
  },
  {
    id: '12',
    organizationId: 'org-2',
    code: 'PROJ-2022-012',
    title: 'FINANCE Development Project 12',
    name: 'FINANCE Development Project 12',
    managerName: 'Aisha Kamara',
    description: 'Improving access to microfinance and financial literacy for small business owners and rural entrepreneurs.',
    status: ProjectStatusEnum.COMPLETED,
    priority: ProjectPriorityEnum.MEDIUM,
    type: ProjectTypeEnum.CAPACITY_BUILDING,
    country: 'Ghana',
    region: RegionEnum.AFRICA_WEST,
    sector: ProjectSectorEnum.GOVERNANCE,
    subsectors: ['CIVIL_SOCIETY', 'ANTI_CORRUPTION'],
    budget: {
      total: 1600000,
      spent: 1560000,
      remaining: 40000,
      currency: 'USD',
    },
    timeline: {
      startDate: '2022-06-01',
      endDate: '2024-05-31',
      duration: 24,
      completionPercentage: 100,
    },
    leadOrganization: 'AFD',
    partners: ['Bank of Ghana', 'Local Microfinance Institutions'],
    teamSize: 20,
    tasksCompleted: 132,
    totalTasks: 132,
    createdDate: '2022-04-10',
    updatedDate: '2024-06-01',
  },
];

// Mock Tasks Initial
const initialMockTasks: TaskDTO[] = [
  {
    id: 't1',
    projectId: '1',
    projectTitle: 'EDUCATION Development Project 1',
    title: 'Complete site survey for new school building',
    description: 'Conduct detailed site survey and soil testing for the new primary school construction in Kisumu region.',
    status: 'IN_PROGRESS',
    priority: ProjectPriorityEnum.HIGH,
    assignedTo: ['John Doe', 'Jane Smith'],
    startDate: '2024-03-01',
    dueDate: '2024-03-15',
    tags: ['survey', 'infrastructure'],
  },
  {
    id: 't2',
    projectId: '1',
    projectTitle: 'EDUCATION Development Project 1',
    title: 'Finalize architectural plans',
    description: 'Complete architectural drawings for 3 school buildings and get approval from Ministry of Education.',
    status: 'TODO',
    priority: ProjectPriorityEnum.URGENT,
    assignedTo: ['Architect Team'],
    startDate: '2024-03-05',
    dueDate: '2024-03-10',
    tags: ['design', 'planning'],
  },
  {
    id: 't3',
    projectId: '2',
    projectTitle: 'HEALTH Development Project 2',
    title: 'Conduct community health training',
    description: 'Train 50 community health workers on maternal care and nutrition best practices.',
    status: 'IN_PROGRESS',
    priority: ProjectPriorityEnum.HIGH,
    assignedTo: ['Health Team', 'Dr. Amina Hassan'],
    startDate: '2024-03-10',
    dueDate: '2024-03-20',
    tags: ['training', 'health'],
  },
  {
    id: 't4',
    projectId: '2',
    projectTitle: 'HEALTH Development Project 2',
    title: 'Develop training materials',
    description: 'Create comprehensive training modules on sustainable farming techniques and climate-smart agriculture.',
    status: 'COMPLETED',
    priority: ProjectPriorityEnum.MEDIUM,
    assignedTo: ['Training Department'],
    startDate: '2024-02-01',
    dueDate: '2024-02-28',
    tags: ['materials', 'agriculture'],
  },
  {
    id: 't5',
    projectId: '4',
    projectTitle: 'INFRASTRUCTURE Development Project 4',
    title: 'Install water filtration systems',
    description: 'Install and test 12 water filtration units in selected communities.',
    status: 'IN_PROGRESS',
    priority: ProjectPriorityEnum.URGENT,
    assignedTo: ['Engineering Team', 'Michael Brown'],
    startDate: '2024-03-01',
    dueDate: '2024-03-25',
    tags: ['installation', 'water'],
  },
  {
    id: 't6',
    projectId: '1',
    projectTitle: 'EDUCATION Development Project 1',
    title: 'Procurement of construction materials',
    description: 'Source and procure cement, steel, and other construction materials according to approved specifications.',
    status: 'TODO',
    priority: ProjectPriorityEnum.HIGH,
    assignedTo: ['Procurement Team'],
    startDate: '2024-03-15',
    dueDate: '2024-03-30',
    tags: ['procurement', 'materials'],
  },
  {
    id: 't7',
    projectId: '2',
    projectTitle: 'HEALTH Development Project 2',
    title: 'Monthly health monitoring report',
    description: 'Compile and submit monthly monitoring report on maternal and child health indicators.',
    status: 'REVIEW',
    priority: ProjectPriorityEnum.MEDIUM,
    assignedTo: ['M&E Team'],
    startDate: '2024-03-01',
    dueDate: '2024-03-08',
    tags: ['monitoring', 'reporting'],
  },
  {
    id: 't8',
    projectId: '3',
    projectTitle: 'AGRICULTURE Development Project 3',
    title: 'Organize farmer field visits',
    description: 'Coordinate field visits to demonstration farms for 200 smallholder farmers.',
    status: 'TODO',
    priority: ProjectPriorityEnum.MEDIUM,
    assignedTo: ['Field Officers'],
    startDate: '2024-03-20',
    dueDate: '2024-04-10',
    tags: ['fieldwork', 'training'],
  },
  {
    id: 't9',
    projectId: '4',
    projectTitle: 'INFRASTRUCTURE Development Project 4',
    title: 'Community awareness campaign',
    description: 'Launch community awareness campaign on water conservation and sanitation practices.',
    status: 'IN_PROGRESS',
    priority: ProjectPriorityEnum.MEDIUM,
    assignedTo: ['Communications Team', 'Community Mobilizers'],
    startDate: '2024-02-15',
    dueDate: '2024-03-31',
    tags: ['awareness', 'community'],
  },
  {
    id: 't10',
    projectId: '5',
    projectTitle: 'ENVIRONMENT Development Project 5',
    title: 'Baseline vulnerability assessment',
    description: 'Conduct baseline assessment of climate vulnerabilities in target coastal communities.',
    status: 'IN_PROGRESS',
    priority: ProjectPriorityEnum.HIGH,
    assignedTo: ['Research Team'],
    startDate: '2024-02-01',
    dueDate: '2024-03-15',
    tags: ['research', 'assessment'],
  },
];

// Mock Collaborations Initial
const initialMockCollaborations: CollaborationDTO[] = [
  {
    id: 'c1',
    projectId: '1',
    projectTitle: 'EDUCATION Development Project 1',
    partnerOrganization: 'Local NGO Consortium',
    type: 'IMPLEMENTATION',
    status: 'ACTIVE',
    startDate: '2023-06-01',
    contribution: 'Community mobilization, local project management, and stakeholder engagement.',
  },
  {
    id: 'c2',
    projectId: '2',
    projectTitle: 'HEALTH Development Project 2',
    partnerOrganization: 'Farmers Association of Senegal',
    type: 'TECHNICAL',
    status: 'ACTIVE',
    startDate: '2024-01-01',
    contribution: 'Training delivery, farmer outreach, and on-ground technical support.',
  },
  {
    id: 'c3',
    projectId: '3',
    projectTitle: 'AGRICULTURE Development Project 3',
    partnerOrganization: 'World Health Organization (WHO)',
    type: 'TECHNICAL',
    status: 'ACTIVE',
    startDate: '2023-03-01',
    contribution: 'Technical guidance on health protocols and capacity building of health workers.',
  },
  {
    id: 'c4',
    projectId: '1',
    projectTitle: 'EDUCATION Development Project 1',
    partnerOrganization: 'Ministry of Education Kenya',
    type: 'IMPLEMENTATION',
    status: 'ACTIVE',
    startDate: '2023-06-01',
    contribution: 'Regulatory approvals, curriculum development, and teacher training coordination.',
  },
  {
    id: 'c5',
    projectId: '4',
    projectTitle: 'INFRASTRUCTURE Development Project 4',
    partnerOrganization: 'WaterAid International',
    type: 'TECHNICAL',
    status: 'ACTIVE',
    startDate: '2023-07-01',
    contribution: 'Technical expertise on water systems design and community WASH training.',
  },
  {
    id: 'c6',
    projectId: '4',
    projectTitle: 'INFRASTRUCTURE Development Project 4',
    partnerOrganization: 'Government of Tanzania - Water Ministry',
    type: 'IMPLEMENTATION',
    status: 'ACTIVE',
    startDate: '2023-07-01',
    contribution: 'Policy coordination, land access facilitation, and sustainability planning.',
  },
  {
    id: 'c7',
    projectId: '2',
    projectTitle: 'HEALTH Development Project 2',
    partnerOrganization: 'Ministry of Agriculture Senegal',
    type: 'ADVISORY',
    status: 'ACTIVE',
    startDate: '2024-01-01',
    contribution: 'Policy guidance, extension services coordination, and research collaboration.',
  },
  {
    id: 'c8',
    projectId: '5',
    projectTitle: 'ENVIRONMENT Development Project 5',
    partnerOrganization: 'Local Research Institutions Bangladesh',
    type: 'TECHNICAL',
    status: 'ACTIVE',
    startDate: '2024-04-01',
    contribution: 'Climate data analysis, vulnerability assessments, and adaptation strategy development.',
  },
  {
    id: 'c9',
    projectId: '3',
    projectTitle: 'AGRICULTURE Development Project 3',
    partnerOrganization: 'Ministry of Health Ethiopia',
    type: 'IMPLEMENTATION',
    status: 'ACTIVE',
    startDate: '2023-03-01',
    contribution: 'Healthcare facilities coordination, medical supplies procurement, and health workforce management.',
  },
  {
    id: 'c10',
    projectId: '5',
    projectTitle: 'ENVIRONMENT Development Project 5',
    partnerOrganization: 'Government of Bangladesh - Environment Ministry',
    type: 'FUNDING',
    status: 'PENDING',
    startDate: '2024-04-01',
    contribution: 'Co-financing agreement for adaptation infrastructure and community resilience programs.',
  },
];

// Mock Templates Initial
const initialMockTemplates: ProjectTemplateDTO[] = [
  {
    id: 'tmp1',
    name: 'Education Infrastructure Standard',
    description: 'Standard template for school construction and renovation projects',
    sector: ProjectSectorEnum.EDUCATION,
    type: ProjectTypeEnum.INFRASTRUCTURE,
    estimatedDuration: 18,
    estimatedBudget: 2000000,
    usageCount: 24,
    rating: 4.8,
    createdBy: 'World Bank',
    createdDate: '2022-05-10',
  },
  {
    id: 'tmp2',
    name: 'Health System Strengthening',
    description: 'Comprehensive template for health system improvement projects',
    sector: ProjectSectorEnum.HEALTH,
    type: ProjectTypeEnum.DEVELOPMENT,
    estimatedDuration: 24,
    estimatedBudget: 3000000,
    usageCount: 18,
    rating: 4.6,
    createdBy: 'WHO',
    createdDate: '2022-08-15',
  },
  {
    id: 'tmp3',
    name: 'Agricultural Capacity Building',
    description: 'Farmer training and sustainable agriculture promotion template',
    sector: ProjectSectorEnum.AGRICULTURE,
    type: ProjectTypeEnum.CAPACITY_BUILDING,
    estimatedDuration: 18,
    estimatedBudget: 850000,
    usageCount: 32,
    rating: 4.7,
    createdBy: 'FAO',
    createdDate: '2022-03-20',
  },
  {
    id: 'tmp4',
    name: 'WASH Infrastructure Development',
    description: 'Water supply and sanitation infrastructure projects',
    sector: ProjectSectorEnum.WATER_SANITATION,
    type: ProjectTypeEnum.INFRASTRUCTURE,
    estimatedDuration: 24,
    estimatedBudget: 4000000,
    usageCount: 15,
    rating: 4.5,
    createdBy: 'UNICEF',
    createdDate: '2022-06-30',
  },
];

export const ProjectsProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [projects, setProjects] = useState<ProjectListDTOInternal[]>(initialMockProjects);
  const [tasks, setTasks] = useState<TaskDTO[]>(initialMockTasks);
  const [collaborations, setCollaborations] = useState<CollaborationDTO[]>(initialMockCollaborations);
  const [templates, setTemplates] = useState<ProjectTemplateDTO[]>(initialMockTemplates);

  const addProject = (project: ProjectListDTOInternal) => {
    setProjects((prev) => [project, ...prev]);
  };

  const updateProject = (id: string, updatedProject: Partial<ProjectListDTOInternal>) => {
    setProjects((prev) =>
      prev.map((project) =>
        project.id === id ? { ...project, ...updatedProject, updatedDate: new Date().toISOString().split('T')[0] } : project
      )
    );
  };

  const deleteProject = (id: string) => {
    setProjects((prev) => prev.filter((project) => project.id !== id));
  };

  const getProjectById = (id: string) => {
    return projects.find((project) => project.id === id);
  };

  const addTask = (task: TaskDTO) => {
    setTasks((prev) => [task, ...prev]);
  };

  const addCollaboration = (collaboration: CollaborationDTO) => {
    setCollaborations((prev) => [collaboration, ...prev]);
  };

  return (
    <ProjectsContext.Provider
      value={{
        projects,
        addProject,
        updateProject,
        deleteProject,
        getProjectById,
        tasks,
        addTask,
        collaborations,
        addCollaboration,
        templates,
      }}
    >
      {children}
    </ProjectsContext.Provider>
  );
};

export const useProjectsContext = () => {
  const context = useContext(ProjectsContext);
  if (!context) {
    throw new Error('useProjectsContext must be used within a ProjectsProvider');
  }
  return context;
};