export interface PhoneCountryCode {
  country: string;
  isoCode: string;
  dialCode: string;
}

export const phoneCountryCodes: PhoneCountryCode[] = [
  { country: 'Afghanistan', isoCode: 'AF', dialCode: '+93' },
  { country: 'Albania', isoCode: 'AL', dialCode: '+355' },
  { country: 'Algeria', isoCode: 'DZ', dialCode: '+213' },
  { country: 'Andorra', isoCode: 'AD', dialCode: '+376' },
  { country: 'Angola', isoCode: 'AO', dialCode: '+244' },
  { country: 'Antigua and Barbuda', isoCode: 'AG', dialCode: '+1' },
  { country: 'Argentina', isoCode: 'AR', dialCode: '+54' },
  { country: 'Armenia', isoCode: 'AM', dialCode: '+374' },
  { country: 'Australia', isoCode: 'AU', dialCode: '+61' },
  { country: 'Austria', isoCode: 'AT', dialCode: '+43' },
  { country: 'Azerbaijan', isoCode: 'AZ', dialCode: '+994' },
  { country: 'Bahamas', isoCode: 'BS', dialCode: '+1' },
  { country: 'Bahrain', isoCode: 'BH', dialCode: '+973' },
  { country: 'Bangladesh', isoCode: 'BD', dialCode: '+880' },
  { country: 'Barbados', isoCode: 'BB', dialCode: '+1' },
  { country: 'Belarus', isoCode: 'BY', dialCode: '+375' },
  { country: 'Belgium', isoCode: 'BE', dialCode: '+32' },
  { country: 'Belize', isoCode: 'BZ', dialCode: '+501' },
  { country: 'Benin', isoCode: 'BJ', dialCode: '+229' },
  { country: 'Bhutan', isoCode: 'BT', dialCode: '+975' },
  { country: 'Bolivia', isoCode: 'BO', dialCode: '+591' },
  { country: 'Bosnia and Herzegovina', isoCode: 'BA', dialCode: '+387' },
  { country: 'Botswana', isoCode: 'BW', dialCode: '+267' },
  { country: 'Brazil', isoCode: 'BR', dialCode: '+55' },
  { country: 'Brunei', isoCode: 'BN', dialCode: '+673' },
  { country: 'Bulgaria', isoCode: 'BG', dialCode: '+359' },
  { country: 'Burkina Faso', isoCode: 'BF', dialCode: '+226' },
  { country: 'Burundi', isoCode: 'BI', dialCode: '+257' },
  { country: 'Cambodia', isoCode: 'KH', dialCode: '+855' },
  { country: 'Cameroon', isoCode: 'CM', dialCode: '+237' },
  { country: 'Canada', isoCode: 'CA', dialCode: '+1' },
  { country: 'Cape Verde', isoCode: 'CV', dialCode: '+238' },
  { country: 'Central African Republic', isoCode: 'CF', dialCode: '+236' },
  { country: 'Chad', isoCode: 'TD', dialCode: '+235' },
  { country: 'Chile', isoCode: 'CL', dialCode: '+56' },
  { country: 'China', isoCode: 'CN', dialCode: '+86' },
  { country: 'Colombia', isoCode: 'CO', dialCode: '+57' },
  { country: 'Comoros', isoCode: 'KM', dialCode: '+269' },
  { country: 'Congo (Republic of)', isoCode: 'CG', dialCode: '+242' },
  { country: 'Costa Rica', isoCode: 'CR', dialCode: '+506' },
  { country: 'Croatia', isoCode: 'HR', dialCode: '+385' },
  { country: 'Cuba', isoCode: 'CU', dialCode: '+53' },
  { country: 'Cyprus', isoCode: 'CY', dialCode: '+357' },
  { country: 'Czech Republic', isoCode: 'CZ', dialCode: '+420' },
  { country: 'Denmark', isoCode: 'DK', dialCode: '+45' },
  { country: 'Djibouti', isoCode: 'DJ', dialCode: '+253' },
  { country: 'Dominica', isoCode: 'DM', dialCode: '+1' },
  { country: 'Dominican Republic', isoCode: 'DO', dialCode: '+1' },
  { country: 'Ecuador', isoCode: 'EC', dialCode: '+593' },
  { country: 'Egypt', isoCode: 'EG', dialCode: '+20' },
  { country: 'El Salvador', isoCode: 'SV', dialCode: '+503' },
  { country: 'Equatorial Guinea', isoCode: 'GQ', dialCode: '+240' },
  { country: 'Eritrea', isoCode: 'ER', dialCode: '+291' },
  { country: 'Estonia', isoCode: 'EE', dialCode: '+372' },
  { country: 'Eswatini', isoCode: 'SZ', dialCode: '+268' },
  { country: 'Ethiopia', isoCode: 'ET', dialCode: '+251' },
  { country: 'Fiji', isoCode: 'FJ', dialCode: '+679' },
  { country: 'Finland', isoCode: 'FI', dialCode: '+358' },
  { country: 'France', isoCode: 'FR', dialCode: '+33' },
  { country: 'Gabon', isoCode: 'GA', dialCode: '+241' },
  { country: 'Gambia', isoCode: 'GM', dialCode: '+220' },
  { country: 'Georgia', isoCode: 'GE', dialCode: '+995' },
  { country: 'Germany', isoCode: 'DE', dialCode: '+49' },
  { country: 'Ghana', isoCode: 'GH', dialCode: '+233' },
  { country: 'Greece', isoCode: 'GR', dialCode: '+30' },
  { country: 'Grenada', isoCode: 'GD', dialCode: '+1' },
  { country: 'Guatemala', isoCode: 'GT', dialCode: '+502' },
  { country: 'Guinea', isoCode: 'GN', dialCode: '+224' },
  { country: 'Guinea Bissau', isoCode: 'GW', dialCode: '+245' },
  { country: 'Guyana', isoCode: 'GY', dialCode: '+592' },
  { country: 'Haiti', isoCode: 'HT', dialCode: '+509' },
  { country: 'Honduras', isoCode: 'HN', dialCode: '+504' },
  { country: 'Hong Kong', isoCode: 'HK', dialCode: '+852' },
  { country: 'Hungary', isoCode: 'HU', dialCode: '+36' },
  { country: 'Iceland', isoCode: 'IS', dialCode: '+354' },
  { country: 'India', isoCode: 'IN', dialCode: '+91' },
  { country: 'Indonesia', isoCode: 'ID', dialCode: '+62' },
  { country: 'Iran', isoCode: 'IR', dialCode: '+98' },
  { country: 'Iraq', isoCode: 'IQ', dialCode: '+964' },
  { country: 'Ireland', isoCode: 'IE', dialCode: '+353' },
  { country: 'Israel', isoCode: 'IL', dialCode: '+972' },
  { country: 'Italy', isoCode: 'IT', dialCode: '+39' },
  { country: 'Jamaica', isoCode: 'JM', dialCode: '+1' },
  { country: 'Japan', isoCode: 'JP', dialCode: '+81' },
  { country: 'Jordan', isoCode: 'JO', dialCode: '+962' },
  { country: 'Kazakhstan', isoCode: 'KZ', dialCode: '+7' },
  { country: 'Kenya', isoCode: 'KE', dialCode: '+254' },
  { country: 'Kuwait', isoCode: 'KW', dialCode: '+965' },
  { country: 'Kyrgyzstan', isoCode: 'KG', dialCode: '+996' },
  { country: 'Laos', isoCode: 'LA', dialCode: '+856' },
  { country: 'Latvia', isoCode: 'LV', dialCode: '+371' },
  { country: 'Lebanon', isoCode: 'LB', dialCode: '+961' },
  { country: 'Lesotho', isoCode: 'LS', dialCode: '+266' },
  { country: 'Liberia', isoCode: 'LR', dialCode: '+231' },
  { country: 'Libya', isoCode: 'LY', dialCode: '+218' },
  { country: 'Liechtenstein', isoCode: 'LI', dialCode: '+423' },
  { country: 'Lithuania', isoCode: 'LT', dialCode: '+370' },
  { country: 'Luxembourg', isoCode: 'LU', dialCode: '+352' },
  { country: 'Malaysia', isoCode: 'MY', dialCode: '+60' },
  { country: 'Maldives', isoCode: 'MV', dialCode: '+960' },
  { country: 'Mali', isoCode: 'ML', dialCode: '+223' },
  { country: 'Malta', isoCode: 'MT', dialCode: '+356' },
  { country: 'Mexico', isoCode: 'MX', dialCode: '+52' },
  { country: 'Moldova', isoCode: 'MD', dialCode: '+373' },
  { country: 'Monaco', isoCode: 'MC', dialCode: '+377' },
  { country: 'Mongolia', isoCode: 'MN', dialCode: '+976' },
  { country: 'Montenegro', isoCode: 'ME', dialCode: '+382' },
  { country: 'Morocco', isoCode: 'MA', dialCode: '+212' },
  { country: 'Mozambique', isoCode: 'MZ', dialCode: '+258' },
  { country: 'Myanmar', isoCode: 'MM', dialCode: '+95' },
  { country: 'Namibia', isoCode: 'NA', dialCode: '+264' },
  { country: 'Nepal', isoCode: 'NP', dialCode: '+977' },
  { country: 'Netherlands', isoCode: 'NL', dialCode: '+31' },
  { country: 'New Zealand', isoCode: 'NZ', dialCode: '+64' },
  { country: 'Nicaragua', isoCode: 'NI', dialCode: '+505' },
  { country: 'Niger', isoCode: 'NE', dialCode: '+227' },
  { country: 'Nigeria', isoCode: 'NG', dialCode: '+234' },
  { country: 'North Macedonia', isoCode: 'MK', dialCode: '+389' },
  { country: 'Norway', isoCode: 'NO', dialCode: '+47' },
  { country: 'Oman', isoCode: 'OM', dialCode: '+968' },
  { country: 'Pakistan', isoCode: 'PK', dialCode: '+92' },
  { country: 'Panama', isoCode: 'PA', dialCode: '+507' },
  { country: 'Paraguay', isoCode: 'PY', dialCode: '+595' },
  { country: 'Peru', isoCode: 'PE', dialCode: '+51' },
  { country: 'Philippines', isoCode: 'PH', dialCode: '+63' },
  { country: 'Poland', isoCode: 'PL', dialCode: '+48' },
  { country: 'Portugal', isoCode: 'PT', dialCode: '+351' },
  { country: 'Qatar', isoCode: 'QA', dialCode: '+974' },
  { country: 'Romania', isoCode: 'RO', dialCode: '+40' },
  { country: 'Russia', isoCode: 'RU', dialCode: '+7' },
  { country: 'Rwanda', isoCode: 'RW', dialCode: '+250' },
  { country: 'Saudi Arabia', isoCode: 'SA', dialCode: '+966' },
  { country: 'Senegal', isoCode: 'SN', dialCode: '+221' },
  { country: 'Serbia', isoCode: 'RS', dialCode: '+381' },
  { country: 'Singapore', isoCode: 'SG', dialCode: '+65' },
  { country: 'Slovakia', isoCode: 'SK', dialCode: '+421' },
  { country: 'Slovenia', isoCode: 'SI', dialCode: '+386' },
  { country: 'South Africa', isoCode: 'ZA', dialCode: '+27' },
  { country: 'South Korea', isoCode: 'KR', dialCode: '+82' },
  { country: 'Spain', isoCode: 'ES', dialCode: '+34' },
  { country: 'Sri Lanka', isoCode: 'LK', dialCode: '+94' },
  { country: 'Sweden', isoCode: 'SE', dialCode: '+46' },
  { country: 'Switzerland', isoCode: 'CH', dialCode: '+41' },
  { country: 'Taiwan', isoCode: 'TW', dialCode: '+886' },
  { country: 'Tanzania', isoCode: 'TZ', dialCode: '+255' },
  { country: 'Thailand', isoCode: 'TH', dialCode: '+66' },
  { country: 'Tunisia', isoCode: 'TN', dialCode: '+216' },
  { country: 'Turkey', isoCode: 'TR', dialCode: '+90' },
  { country: 'Uganda', isoCode: 'UG', dialCode: '+256' },
  { country: 'Ukraine', isoCode: 'UA', dialCode: '+380' },
  { country: 'United Arab Emirates', isoCode: 'AE', dialCode: '+971' },
  { country: 'United Kingdom', isoCode: 'GB', dialCode: '+44' },
  { country: 'United States', isoCode: 'US', dialCode: '+1' },
  { country: 'Uruguay', isoCode: 'UY', dialCode: '+598' },
  { country: 'Uzbekistan', isoCode: 'UZ', dialCode: '+998' },
  { country: 'Venezuela', isoCode: 'VE', dialCode: '+58' },
  { country: 'Vietnam', isoCode: 'VN', dialCode: '+84' },
  { country: 'Zambia', isoCode: 'ZM', dialCode: '+260' },
  { country: 'Zimbabwe', isoCode: 'ZW', dialCode: '+263' },
].sort((a, b) => a.country.localeCompare(b.country));
